---
- block:
    - name: Down monitor container
      docker_service:
        project_src: /srv/monitor
        files:
          - docker-compose.yml
          - 'docker-compose.{{ monitor_env }}.yml'
        state: absent
        remove_volumes: '{{ "no" if monitor_persistent else "yes" }}'
  tags: [monitor]
