---
- block:
    - name: Execute identities database migration
      shell:
        cmd: 'docker-compose exec -T php php bin/console doctrine:migrations:migrate {{ _version }} --no-interaction'
        chdir: /srv/identities
  tags: [identities]
