---
- block:
    - name: Download tenants repository
      git:
        repo: '{{ _repository if _credential is none else _repository|replace("//", "//"+_credential+"@") }}'
        version: '{{ version }}'
        dest: /srv/tenants
        force: yes
  tags: [tenants]
