---
- block:
    - name: Retrieve proxy container ip
      include_tasks: /etc/ansible/task/app/proxy/container/property/ip.yml
    - name: Retrieve discovery container ip
      include_tasks: /etc/ansible/task/app/discovery/container/property/ip.yml
    - name: Up microservice container
      include_role:
        name: app/microservice/container/up
      vars:
        _files: '{{ app.microservice.docker|list }}'
        _namespace: '{{ namespace }}'
        _directory: '{{ directory }}/microservice'
        _network: '{{ namespace }}_proxy_default'
        _proxy_host: '{{ proxy_container_ip.stdout }}'
        _database_host: '{{ app.microservice.database.host }}'
        _database_name: '{{ app.microservice.database.name }}'
        _database_user: '{{ app.microservice.database.user }}'
        _database_password: '{{ app.microservice.database.password }}'
        _database_ui_host: '{{ app.microservice.database.ui.host }}'
        _api_env: '{{ env }}'
        _api_secret: '{{ encryption.secret }}'
        _api_host: '{{ app.microservice.api.host }}'
        _api_jwt_pass_phrase: '{{ jwt.pass_phrase }}'
        _api_discovery_host: '{{ discovery_container_ip.stdout }}:8500'
        _api_discovery_credential: '{{ app.discovery.token.master }}'
        _api_encryption: '{{ encryption.encryption }}'
        _api_system_username: '{{ system.username }}'
        _api_system_password: '{{ system.password }}'
        _mock_discovery_host: '{{ app.microservice.mock.discovery.host }}'
  when: app.microservice.enabled
  tags: [microservice]
