---
- name: Stop containers on server
  hosts: server
  become: true
  roles:
    - service/assets/container/stop
    - service/authentication/container/stop
    - service/camunda/container/stop
    - service/cases/container/stop
    - service/cms/container/stop
    - service/identities/container/stop
    - service/records/container/stop
    - service/services/container/stop
    - { role: service/tasks/container/stop, when: edition == 'enterprise' }
