---
- name: Configure proxy host environment variable
  lineinfile:
      path: /srv/camunda/.env
      regexp: '^PROXY_HOST='
      line: 'PROXY_HOST={{ proxy_host }}'

- name: Configure camunda host environment variable
  lineinfile:
      path: /srv/camunda/.env
      regexp: '^VIRTUAL_HOST='
      line: 'VIRTUAL_HOST={{ camunda_host }}'
