---
- name: Configure timezone environment variable
  lineinfile:
      path: /srv/camunda/.env
      regexp: '^JAVA_OPTS='
      line: 'JAVA_OPTS=Djava.security.egd=file:/dev/./urandom -Duser.timezone={{ camunda_timezone }}'

- name: Configure proxy host environment variable
  lineinfile:
      path: /srv/camunda/.env
      regexp: '^PROXY_HOST='
      line: 'PROXY_HOST={{ camunda_proxy_host }}'

- name: Configure virtual host environment variable
  lineinfile:
      path: /srv/camunda/.env
      regexp: '^VIRTUAL_HOST='
      line: 'VIRTUAL_HOST={{ camunda_virtual_host }}'

- name: Configure directory environment variable
  lineinfile:
      path: /srv/camunda/.env
      regexp: '^DIRECTORY='
      line: 'DIRECTORY={{ camunda_directory }}'
