---
- block:
    - name: Create key-value entry
      shell:
        cmd: 'docker-compose exec -T bootstrap env CONSUL_HTTP_TOKEN={{ _credential }} consul kv put "{{ item.key }}" "{{ item.value }}"'
        chdir: /srv/discovery
      with_dict: '{{ _data }}'
  tags: [discovery]
