---
- block:
    - name: Delete admin repository branch
      include_role:
        name: app/admin/repository/branch/delete
      vars:
        _repository: '{{ app.admin.repository }}'
        _branch: '{{ branch }}'
  when: app.admin.enabled
  tags: [admin]
