---
- block:
    - name: Down cases container
      docker_service:
        project_src: /srv/cases
        files:
          - docker-compose.yml
          - 'docker-compose.{{ cases_env }}.yml'
        state: absent
        remove_volumes: '{{ "no" if cases_persistent else "yes" }}'
  tags: [cases]
