---
- name: Compile container/stop task list
  hosts: platform
  become: true
  tasks:
    - name: Compile files
      compile:
        app: '{{ app }}'
        directory: /etc/ansible/task/app/*
        task: container/stop
        order: desc
      register: _result
  tags: [always]

- name: Stop containers
  hosts: app
  become: true
  tasks:
    - name: Include compiled task list
      include_tasks: '{{ _file }}'
      with_items: '{{ hostvars["platform"]["_result"]["tasks"] }}'
      loop_control:
        loop_var: _file
      tags: [always]
