---
- block:
    - name: Run tenants health check
      shell:
        cmd: 'docker-compose exec -T api wget -qO- http://{{ _host }}'
        chdir: /srv/tenants
      register: _result
      changed_when: false
    - name: Display tenants health check result
      debug:
        msg: '{{ "Healthy" if (_result.stdout|from_json).healthy else "Not Health" }}'
  tags: [tenants]
