---
- block:
    - name: Define topics jwt variables
      set_fact:
        topics_jwt_key_pass_phrase: '{{ platform.jwt.pass_phrase }}'
    - name: Configure topics jwt key pass phrase
      include_role:
        name: app/topics/jwt/configure
  when: app.topics.enabled
  tags: [topics]
