---
- name: Compile jwt list
  hosts: sdk
  become: true
  tasks:
      - name: ...
        include_tasks: /etc/ansible/task/compiler/jwt/configure.yml

- name: Configure jwt key pass phrases
  hosts: server
  become: true
  tasks:
      - name: Define jwt variables
        set_fact:
            jwt_key_pass_phrase: '{{ jwt.key_pass_phase }}'

      - name: Include compiled list
        include_tasks: '{{ file }}'
        with_items: '{{ hostvars["sdk"]["files"] }}'
        loop_control:
            loop_var: file
