---
- import_playbook: system/initialize.yml
- import_playbook: system/setup.yml
- import_playbook: repository/download.yml
- import_playbook: repository/override.yml
- import_playbook: jwt/download.yml
- import_playbook: proxy/container/up.yml
- import_playbook: container/env/configure.yml
- import_playbook: container/up.yml
- import_playbook: jwt/configure.yml
- import_playbook: database/migrate.yml
- import_playbook: database/data/load.yml
- import_playbook: config/configure.yml
