all:
    hosts:
        sdk:
            ansible_connection: local
        server:
            ansible_host: ~
            ansible_port: 22
            ansible_ssh_private_key_file: /root/.ssh/prod/key
    vars:
        project: ds
        directory: /srv
        env: prod
        timezone: UTC
        data: ~
        jwt:
            private_key: /root/resource/jwt/prod/key
            public_key: /root/resource/jwt/prod/key.pub
            key_pass_phase: ~
        mail:
            transport: smtp
            host: 127.0.0.1
            port: ~
            username: admin@localhost
            password: ~
        util:
            adminer: /root/resource/util/adminer.php
        admin:
            enabled: true
            repository: https://github.com/DigitalState/Admin.git
            version: master
            host: admin.prod.ds
        assets:
            enabled: true
            repository: https://github.com/DigitalState/Assets.git
            version: master
            host: api.assets.prod.ds
        authentication:
            enabled: true
            repository: https://github.com/DigitalState/Authentication.git
            version: master
            host: api.authentication.prod.ds
        camunda:
            enabled: true
            repository: https://github.com/DigitalState/Camunda.git
            version: master
            host: api.camunda.prod.ds
        cases:
            enabled: true
            repository: https://github.com/DigitalState/Cases.git
            version: master
            host: api.cases.prod.ds
        cms:
            enabled: true
            repository: https://github.com/DigitalState/Cms.git
            version: master
            host: api.cms.prod.ds
        core:
            enabled: false
            repository: https://github.com/DigitalState/Core.git
            version: master
        discovery:
            enabled: false
            repository: https://github.com/DigitalState/Discovery.git
            version: master
            host: api.discovery.prod.ds
        documentation:
            enabled: false
            repository: https://github.com/DigitalState/Documentation.git
            version: master
        formio:
            enabled: true
            repository: https://github.com/DigitalState/Formio.git
            version: master
            host: api.formio.prod.ds
        guide:
            enabled: false
            repository: https://github.com/DigitalState/Guide.git
            version: master
        identities:
            enabled: true
            repository: https://github.com/DigitalState/Identities.git
            version: master
            host: api.identities.prod.ds
        interactions:
            enabled: false
            repository: https://github.com/DigitalState/Interactions.git
            version: master
            host: api.interactions.prod.ds
        logs:
            enabled: false
            repository: https://github.com/DigitalState/Logs.git
            version: master
            host: api.logs.prod.ds
        monitor:
            enabled: false
            repository: https://github.com/DigitalState/Monitor.git
            version: master
            host: monitor.prod.ds
        portal:
            enabled: true
            version: master
            repository: https://github.com/DigitalState/Portal.git
            host: portal.prod.ds
        proxy:
            enabled: true
            repository: https://github.com/DigitalState/Proxy.git
            version: master
            port: 443
        records:
            enabled: true
            version: master
            repository: https://github.com/DigitalState/Records.git
            host: api.records.prod.ds
        services:
            enabled: true
            repository: https://github.com/DigitalState/Services.git
            version: master
            host: api.services.prod.ds
        tasks:
            enabled: false
            repository: https://github.com/DigitalState/Tasks.git
            version: master
            host: api.tasks.prod.ds
        topics:
            enabled: false
            repository: https://github.com/DigitalState/Topics.git
            version: master
            host: api.topics.prod.ds
        ui:
            enabled: false
            repository: https://github.com/DigitalState/Ui.git
            version: master
