all:
    hosts:
        server:
            ansible_host: ~
            ansible_port: 22
            ansible_ssh_private_key_file: /root/.ssh/prod/key

    vars:
        documentation: ~
        guide: ~
        api: master
        assets: master
        authentication: master
        camunda: master
        cases: master
        cms: master
        core: ~
        discovery: ~
        formio: master
        identities: master
        interactions: ~
        logs: master
        records: master
        services: master
        tasks: ~
        topics: ~
        admin: master
        monitor: master
        portal: master
        ui: ~

        assets_host: api.assets.ds
        authentication_host: api.authentication.ds
        camunda_host: api.camunda.ds
        cases_host: api.cases.ds
        cms_host: api.cms.ds
        discovery_host: api.discovery.ds
        formio_host: api.formio.ds
        identities_host: api.identities.ds
        interactions_host: api.interactions.ds
        logs_host: api.logs.ds
        records_host: api.records.ds
        services_host: api.services.ds
        tasks_host: api.tasks.ds
        topics_host: api.topics.ds

        jwt_private_key: /root/resource/security/jwt/prod/key
        jwt_public_key: /root/resource/security/jwt/prod/key.pub
        jwt_key_pass_phrase: ~

        fixtures: dev
