all:
    hosts:
        server:
            ansible_host: ~
            ansible_port: 22
            ansible_ssh_private_key_file: /root/.ssh/prod/key

    vars:
        documentation: ~
        guide: ~
        api: master
        assets: master
        authentication: master
        camunda: master
        cases: master
        cms: master
        core: ~
        discovery: ~
        formio: master
        identities: master
        interactions: ~
        logs: master
        records: master
        services: master
        tasks: ~
        topics: ~
        admin: master
        monitor: master
        portal: master
        ui: ~

        assets_host: http://api.assets.ds
        authentication_host: http://api.authentication.ds
        camunda_host: http://api.camunda.ds/engine-rest
        cases_host: http://api.cases.ds
        cms_host: http://api.cms.ds
        discovery_host: http://api.discovery.ds
        formio_host: http://api.formio.ds
        identities_host: http://api.identities.ds
        interactions_host: http://api.interactions.ds
        logs_host: http://api.logs.ds
        records_host: http://api.records.ds
        services_host: http://api.services.ds
        tasks_host: http://api.tasks.ds
        topics_host: http://api.topics.ds

        jwt_private_key: /root/resource/security/jwt/prod/key
        jwt_public_key: /root/resource/security/jwt/prod/key.pub
        jwt_key_pass_phrase: ~

        fixtures: dev
