all:
    hosts:
        server:
            ansible_host: ~
            ansible_port: 22
            ansible_ssh_private_key_file: /root/.ssh/prod/key

    vars:
        ### General ###########################################################

        env: prod

        directory: /srv

        jwt_private_key: /root/resource/jwt/prod/key
        jwt_public_key: /root/resource/jwt/prod/key.pub
        jwt_key_pass_phrase: ~

        data: dev

        ### Documentation #####################################################

        documentation: ~
        documentation_version: master

        ### Guide #############################################################

        guide: ~
        guide_version: master

        ### Proxy #############################################################

        proxy: enabled
        proxy_version: master

        ### Assets ############################################################

        assets: ~
        assets_version: master
        assets_host: api.assets.ds

        ### Authentication ####################################################

        authentication: enabled
        authentication_version: master
        authentication_host: api.authentication.ds

        ### Camunda ###########################################################

        camunda: ~
        camunda_version: master
        camunda_host: api.camunda.ds

        ### Cases #############################################################

        cases: ~
        cases_version: master
        cases_host: api.cases.ds

        ### Cms ###############################################################

        cms: ~
        cms_version: master
        cms_host: api.cms.ds

        ### Discovery #########################################################

        discovery: ~
        discovery_version: master
        discovery_host: api.discovery.ds

        ### Formio ############################################################

        formio: ~
        formio_version: master
        formio_host: api.formio.ds

        ### Identities ########################################################

        identities: enabled
        identities_version: master
        identities_host: api.identities.ds

        ### Interactions ######################################################

        interactions: ~
        interactions_version: master
        interactions_host: api.interactions.ds

        ### Logs ##############################################################

        logs: ~
        logs_version: master
        logs_host: api.logs.ds

        ### Records ###########################################################

        records: ~
        records_version: master
        records_host: api.records.ds

        ### Services ##########################################################

        services: ~
        services_version: master
        services_host: api.services.ds

        ### Tasks #############################################################

        tasks: ~
        tasks_version: master
        tasks_host: api.tasks.ds

        ### Topics ############################################################

        topics: ~
        topics_version: master
        topics_host: api.topics.ds

        ### Core ##############################################################

        core: ~
        core_version: master

        ### Admin #############################################################

        admin: ~
        admin_version: master

        ### Monitor ###########################################################

        monitor: ~
        monitor_version: master

        ### Portal ############################################################

        portal: ~
        portal_version: master

        ### Ui ################################################################

        ui: ~
        ui_version: master
