all:
    hosts:
        sdk:
            ansible_connection: local
        server:
            ansible_host: ~
            ansible_port: 22
            ansible_ssh_private_key_file: /root/.ssh/prod/key
    vars:
        project: ds
        directory: /srv
        env: prod
        timezone: UTC
        encryption:
            secret: ~
        jwt:
            private_key: /root/resource/jwt/prod/key
            public_key: /root/resource/jwt/prod/key.pub
            key_pass_phrase: ~
        mail:
            transport: smtp
            host: 127.0.0.1
            port: ~
            username: mail@localhost
            password: ~
        fixtures: ~
        user:
            system:
                password: ~
            anonymous:
                password: ~
            admin:
                password: ~
        util:
            adminer: ~
        admin:
            enabled: true
            repository: https://github.com/DigitalState/Admin.git
            version: 0.1.0
            host: admin.prod.ds
        assets:
            enabled: true
            repository: https://github.com/DigitalState/Assets.git
            version: 0.1.0
            host: api.assets.prod.ds
            database:
                host: assets_db
                port: 5432
                name: assets
                username: assets
                password: ~
        authentication:
            enabled: true
            repository: https://github.com/DigitalState/Authentication.git
            version: 0.1.0
            host: api.authentication.prod.ds
            database:
                host: authentication_db
                port: 5432
                name: authentication
                username: authentication
                password: ~
        camunda:
            enabled: true
            repository: https://github.com/DigitalState/Camunda.git
            version: 0.1.0
            host: api.camunda.prod.ds
            username: admin@staff.ds
            password: ~
        cases:
            enabled: true
            repository: https://github.com/DigitalState/Cases.git
            version: 0.1.0
            host: api.cases.prod.ds
            database:
                host: cases_db
                port: 5432
                name: cases
                username: cases
                password: ~
        cms:
            enabled: true
            repository: https://github.com/DigitalState/Cms.git
            version: 0.1.0
            host: api.cms.prod.ds
            database:
                host: cms_db
                port: 5432
                name: cms
                username: cms
                password: ~
        core:
            enabled: false
            repository: https://github.com/DigitalState/Core.git
            version: 0.1.0
        discovery:
            enabled: true
            repository: https://github.com/DigitalState/Discovery.git
            version: 0.1.0
            host: api.discovery.prod.ds
        documentation:
            enabled: false
            repository: https://github.com/DigitalState/Documentation.git
            version: 0.1.0
        formio:
            enabled: true
            repository: https://github.com/DigitalState/Formio.git
            version: 0.1.5
            host: api.formio.prod.ds
            username: admin@staff.ds
            password: ~
        guide:
            enabled: false
            repository: https://github.com/DigitalState/Guide.git
            version: 0.1.0
        identities:
            enabled: true
            repository: https://github.com/DigitalState/Identities.git
            version: 0.1.0
            host: api.identities.prod.ds
            database:
                host: identities_db
                port: 5432
                name: identities
                username: identities
                password: ~
        interactions:
            enabled: false
            repository: https://github.com/DigitalState/Interactions.git
            version: 0.1.0
            host: api.interactions.prod.ds
            database:
                host: interactions_db
                port: 5432
                name: interactions
                username: interactions
                password: ~
        logs:
            enabled: false
            repository: https://github.com/DigitalState/Logs.git
            version: 0.1.0
            host: api.logs.prod.ds
        monitor:
            enabled: false
            repository: https://github.com/DigitalState/Monitor.git
            version: 0.1.0
            host: monitor.prod.ds
        portal:
            enabled: true
            repository: https://github.com/DigitalState/Portal.git
            version: 0.1.0
            host: portal.prod.ds
        proxy:
            enabled: true
            repository: https://github.com/DigitalState/Proxy.git
            version: 0.1.0
            port: 80
        records:
            enabled: true
            repository: https://github.com/DigitalState/Records.git
            version: 0.1.0
            host: api.records.prod.ds
            database:
                host: records_db
                port: 5432
                name: records
                username: records
                password: ~
        services:
            enabled: true
            repository: https://github.com/DigitalState/Services.git
            version: 0.1.2
            host: api.services.prod.ds
            database:
                host: services_db
                port: 5432
                name: services
                username: services
                password: ~
        tasks:
            enabled: false
            repository: https://github.com/DigitalState/Tasks.git
            version: 0.1.0
            host: api.tasks.prod.ds
            database:
                host: tasks_db
                port: 5432
                name: tasks
                username: tasks
                password: ~
        topics:
            enabled: false
            repository: https://github.com/DigitalState/Topics.git
            version: 0.1.0
            host: api.topics.prod.ds
            database:
                host: topics_db
                port: 5432
                name: topics
                username: topics
                password: ~
        ui:
            enabled: false
            repository: https://github.com/DigitalState/Ui.git
            version: 0.1.0
