---
_env: prod
_compose_project_name: dscms
_network: dsproxy_default
_proxy_host: 127.0.0.1
_nginx_virtual_host: api.cms.ds
_adminer_virtual_host: adminer.cms.ds
_rebrow_virtual_host: rebrow.cms.ds
_discovery_host: api.discovery.ds
_directory: /srv/cms
_database_host: cms_db
_database_port: 5432
_database_name: cms
_database_username: cms
_database_password: cms
