---
- block:
    - name: Download tasks repository
      git:
        repo: '{{ _repository if _credential is none else _repository|replace("//", "//"+_credential+"@") }}'
        version: '{{ _version }}'
        dest: /srv/tasks
        force: yes
  tags: [tasks]
