---
- block:
    - name: Run identities health check
      shell:
        cmd: 'docker-compose exec -T api wget -qO- http://{{ _host }}'
        chdir: /srv/identities
      register: _result
      changed_when: false
    - name: Display identities health check result
      debug:
        msg: '{{ "Healthy" if (_result.stdout|from_json).healthy else "Not Health" }}'
  tags: [identities]
