---
- block:
    - name: Delete authentication repository branch
      include_role:
        name: app/authentication/repository/branch/delete
      vars:
        _repository: '{{ app.authentication.repository }}'
        _branch: '{{ branch }}'
  when: app.authentication.enabled
  tags: [authentication]
