---
- block:
    - name: Run microservice health check
      include_role:
        name: app/microservice/health/run
    - name: Validate microservice health check result
      debug:
        msg: '{{ "Healthy" if (_result.stdout|from_json).healthy else "Not Health" }}'
      failed_when: (_result.stdout|from_json).healthy != true
  tags: [microservice]
