---
- name: Configure assets jwt key pass phrase
  replace:
      path: /srv/service/assets/app/config/parameters.yml
      regexp: 'jwt_key_pass_phrase: '''''
      replace: 'jwt_key_pass_phrase: ''{{ jwt_key_pass_phrase }}'''
