---
authentication:
  enabled: true
  repository: https://github.com/DigitalState/Authentication.git
  version: 0.12.0
  api:
    host: api.authentication.stag.ds
  database:
    host: authentication_database
    port: 5432
    name: authentication
    username: authentication
    password: ~
    ui:
      host: ui.database.authentication.stag.ds
  cache:
    ui:
      host: ui.cache.authentication.stag.ds
