---
cases:
  enabled: true
  repository: https://github.com/DigitalState/Cases.git
  version: 0.8.0
  api:
    host: api.cases.stag.ds
  adminer:
    host: adminer.cases.stag.ds
  rebrow:
    host: rebrow.cases.stag.ds
  database:
    host: cases_database
    port: 5432
    name: cases
    username: cases
    password: ~
  attributes:
    access: true
    tenant: true
