---
cases:
  enabled: true
  repository: https://github.com/DigitalState/Cases.git
  version: 0.10.0
  api:
    host: api.cases.stag.ds
  database:
    host: cases_database
    port: 5432
    name: cases
    username: cases
    password: ~
    ui:
      host: ui.database.cases.stag.ds
  cache:
    ui:
      host: ui.cache.cases.stag.ds
