---
cms:
  enabled: true
  repository: https://github.com/DigitalState/Cms.git
  version: 0.12.0
  api:
    host: api.cms.stag.ds
  database:
    host: cms_database
    port: 5432
    name: cms
    username: cms
    password: ~
    ui:
      host: ui.database.cms.stag.ds
  cache:
    ui:
      host: ui.cache.cms.stag.ds
