---
formio:
  enabled: true
  order: -10
  repository: https://github.com/DigitalState/Formio.git
  version: 0.10.0
  api:
    host: api.formio.stag.ds
  database:
    ui:
      host: adminer.formio.stag.ds
  username: admin@staff.ds
  password: ~
