---
identities:
  enabled: true
  repository: https://github.com/DigitalState/Identities.git
  version: 0.14.0
  api:
    host: api.identities.stag.ds
  database:
    host: identities_database
    port: 5432
    name: identities
    username: identities
    password: ~
    ui:
      host: ui.database.identities.stag.ds
  cache:
    ui:
      host: ui.cache.identities.stag.ds
