---
records:
  enabled: true
  repository: https://github.com/DigitalState/Records.git
  version: 0.8.0
  api:
    host: api.records.stag.ds
  adminer:
    host: adminer.records.stag.ds
  rebrow:
    host: rebrow.records.stag.ds
  database:
    host: records_database
    port: 5432
    name: records
    username: records
    password: ~
  attributes:
    access: true
    tenant: true
