---
records:
  enabled: true
  repository: https://github.com/DigitalState/Records.git
  version: 0.14.0
  api:
    host: api.records.stag.ds
  database:
    host: records_database
    port: 5432
    name: records
    username: records
    password: ~
    ui:
      host: ui.database.records.stag.ds
  cache:
    ui:
      host: ui.cache.records.stag.ds
