---
services:
  enabled: true
  repository: https://github.com/DigitalState/Services.git
  version: 0.13.0
  api:
    host: api.services.stag.ds
  database:
    host: services_database
    port: 5432
    name: services
    username: services
    password: ~
    ui:
      host: ui.database.services.stag.ds
  cache:
    ui:
      host: ui.cache.services.stag.ds
