---
tasks:
  enabled: false
  repository: https://github.com/DigitalState/Tasks.git
  version: 0.7.0
  api:
    host: api.tasks.stag.ds
  adminer:
    host: adminer.tasks.stag.ds
  rebrow:
    host: rebrow.tasks.stag.ds
  database:
    host: tasks_database
    port: 5432
    name: tasks
    username: tasks
    password: ~
  attributes:
    access: true
    tenant: true
