---
tenants:
  enabled: false
  repository: https://github.com/DigitalState/Tenants.git
  version: 0.13.0
  api:
    host: api.tenants.stag.ds
  database:
    host: tenants_database
    port: 5432
    name: tenants
    username: tenants
    password: ~
    ui:
      host: ui.database.tenants.stag.ds
  cache:
    ui:
      host: ui.cache.tenants.stag.ds
