---
topics:
  enabled: false
  repository: https://github.com/DigitalState/Topics.git
  version: 0.8.0
  api:
    host: api.topics.stag.ds
  database:
    host: topics_database
    port: 5432
    name: topics
    username: topics
    password: ~
    ui:
      host: ui.database.topics.stag.ds
  cache:
    ui:
      host: ui.cache.topics.stag.ds
