---
- name: Install python2 dependency for ansible on all remote hosts
  hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Install python2 for ansible
      raw: bash -c 'test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)'
      register: output
      changed_when: output.stdout != ''
    - name: Gathering facts
      setup:
