---
- name: Define identities jwt variables
  set_fact:
      identities_jwt_key_pass_phrase: '{{ jwt.key_pass_phrase }}'

- name: Configure identities jwt key pass phrase
  include_role:
      name: app/identities/jwt/configure
  when: identities.enabled
  tags: [identities]
