---
- block:
    - name: Gather information for topics container
      include_tasks: /etc/ansible/task/app/proxy/container/info.yml
    - name: Up topics container
      include_role:
        name: app/topics/container/up
      vars:
        _env: '{{ env }}'
        _compose_project_name: '{{ namespace }}topics'
        _network: '{{ namespace }}proxy_default'
        _proxy_host: '{{ proxy_container_info_ip.stdout }}'
        _nginx_virtual_host: '{{ app.topics.api.host }}'
        _adminer_virtual_host: '{{ app.topics.adminer.host }}'
        _rebrow_virtual_host: '{{ app.topics.rebrow.host }}'
        _discovery_host: '{{ app.discovery.api.host }}'
        _directory: '{{ directory }}/topics'
        _database_host: '{{ app.topics.database.host }}'
        _database_port: '{{ app.topics.database.port }}'
        _database_name: '{{ app.topics.database.name }}'
        _database_username: '{{ app.topics.database.username }}'
        _database_password: '{{ app.topics.database.password }}'
  when: app.topics.enabled
  tags: [topics]
