---
- name: Configure proxy host environment variable
  lineinfile:
      path: /srv/service/topics/.env
      regexp: '^PROXY_HOST='
      line: 'PROXY_HOST={{ proxy_host }}'

- name: Configure topics host environment variable
  lineinfile:
      path: /srv/service/topics/.env
      regexp: '^VIRTUAL_HOST='
      line: 'VIRTUAL_HOST={{ topics_host }}'
