---
namespace: ds
directory: /srv
timezone: UTC
encryption:
  encryption: ~
  secret: ~
jwt:
  pass_phrase: ~
mail:
  transport: smtp
  host: 127.0.0.1
  port: ~
  username: mail@localhost
  password: ~
integration:
  github:
    id: ~
    secret: ~
  google:
    id: ~
    secret: ~
  twitter:
    id: ~
    secret: ~
system:
  username: system
  password: ~
user:
  system:
    username: system@system.ds
    password: ~
  anonymous:
    username: anonymous@anonymous.ds
    password: ~
  admin:
    username: admin@staff.ds
    password: ~
