---
assets:
  enabled: true
  repository: https://github.com/DigitalState/Assets.git
  version: develop
  api:
    host: api.assets.lab.ds
  adminer:
    host: adminer.assets.lab.ds
  rebrow:
    host: rebrow.assets.lab.ds
  database:
    host: assets_database
    port: 5432
    name: assets
    username: assets
    password: assets
  attributes:
    access: true
    tenant: true
