---
cms:
  enabled: true
  repository: https://github.com/DigitalState/Cms.git
  version: develop
  api:
    host: api.cms.lab.ds
  adminer:
    host: adminer.cms.lab.ds
  rebrow:
    host: rebrow.cms.lab.ds
  database:
    host: cms_database
    port: 5432
    name: cms
    username: cms
    password: cms
  attributes:
    access: true
    tenant: true
