---
formio:
  enabled: true
  order: -10
  repository: https://github.com/DigitalState/Formio.git
  version: develop
  api:
    host: api.formio.lab.ds
  adminer:
    host: adminer.formio.lab.ds
  username: admin@staff.ds
  password: admin
  attributes: {}
