---
tenants:
  enabled: true
  repository: https://github.com/DigitalState/Tenants.git
  version: develop
  api:
    host: api.tenants.lab.ds
  database:
    host: tenants_database
    port: 5432
    name: tenants
    username: tenants
    password: tenants
    ui:
      host: ui.database.tenants.lab.ds
  cache:
    ui:
      host: ui.cache.tenants.lab.ds
