---
topics:
  enabled: false
  repository: https://github.com/DigitalState/Topics.git
  version: develop
  api:
    host: api.topics.lab.ds
  adminer:
    host: adminer.topics.lab.ds
  rebrow:
    host: rebrow.topics.lab.ds
  database:
    host: topics_database
    port: 5432
    name: topics
    username: topics
    password: topics
  attributes:
    access: true
    tenant: true
