---
- name: Configure identities jwt key pass phrase
  lineinfile:
      path: /srv/service/identities/app/config/parameters.yml
      regexp: '^\s{4}jwt_key_pass_phrase:'
      line: '    jwt_key_pass_phrase: ''{{ jwt_key_pass_phrase }}'''
