---
- name: Configure identities jwt key pass phrase
  replace:
      path: /srv/service/identities/app/config/parameters.yml
      regexp: 'jwt_key_pass_phrase: '''''
      replace: 'jwt_key_pass_phrase: ''{{ jwt_key_pass_phrase }}'''
