---
- block:
    - name: Download assets repository
      git:
        repo: '{{ _repository|replace("//", "//"+_credential.username+":"+_credential.password+"@") }}'
        version: '{{ _version }}'
        dest: /srv/assets
        force: yes
  tags: [assets]
