---
- block:
    - name: Download identities jwt private key
      copy:
        src: '{{ _private_key }}'
        dest: /srv/identities/var/jwt/key
        mode: 0600
    - name: Download identities jwt public key
      copy:
        src: '{{ _public_key }}'
        dest: /srv/identities/var/jwt/key.pub
        mode: 0600
  tags: [identities]
