---
- block:
    - name: Execute tenants database migration
      shell:
        cmd: 'docker-compose exec -T php php bin/console doctrine:migrations:migrate {{ _version }} --no-interaction'
        chdir: /srv/tenants
  tags: [tenants]
