---
- name: Compile config list
  hosts: sdk
  become: true
  tasks:
      - name: ...
        include_tasks: /etc/ansible/task/compiler/config/api/configure.yml

- name: Configure api host configs
  hosts: server
  become: true
  tasks:
      - name: Include compiled task list
        include_tasks: '{{ file }}'
        vars:
            config:
                ds_api.api.assets.host: 'http://{{ assets.host }}'
                ds_api.api.authentication.host: 'http://{{ authentication.host }}'
                ds_api.api.camunda.host: 'http://{{ camunda.host }}/engine-rest'
                ds_api.api.cases.host: 'http://{{ cases.host }}'
                ds_api.api.cms.host: 'http://{{ cms.host }}'
                ds_api.api.formio.host: 'http://{{ formio.host }}'
                ds_api.api.identities.host: 'http://{{ identities.host }}'
                ds_api.api.records.host: 'http://{{ records.host }}'
                ds_api.api.services.host: 'http://{{ services.host }}'
                ds_api.api.tasks.host: 'http://{{ tasks.host }}'
        with_items: '{{ hostvars["sdk"]["files"] }}'
        loop_control:
            loop_var: file
