---
- name: Configure host config to proxy container ip
  hosts: server
  become: true
  vars:
      config:
          ds_api.api.assets.host: 'http://{{ assets_host }}'
          ds_api.api.authentication.host: 'http://{{ authentication_host }}'
          ds_api.api.cases.host: 'http://{{ cases_host }}'
          ds_api.api.cms.host: 'http://{{ cms_host }}'
          ds_api.api.identities.host: 'http://{{ identities_host }}'
          ds_api.api.records.host: 'http://{{ records_host }}'
          ds_api.api.services.host: 'http://{{ services_host }}'
          ds_api.api.tasks.host: 'http://{{ tasks_host }}'
          ds_api.api.camunda.host: 'http://{{ camunda_host }}/engine-rest'
          ds_api.api.formio.host: 'http://{{ formio_host }}'
  roles:
      - { role: service/assets/config/set, when: assets is not none }
      - { role: service/authentication/config/set, when: authentication is not none }
      - { role: service/cases/config/set, when: cases is not none }
      - { role: service/cms/config/set, when: cms is not none }
      - { role: service/identities/config/set, when: identities is not none }
      - { role: service/records/config/set, when: records is not none }
      - { role: service/services/config/set, when: services is not none }
      - { role: service/tasks/config/set, when: tasks is not none }
