---
_files: ['docker-compose.yml']
_namespace: ds
_directory: /srv/forms
_network: ds_proxy_default
_proxy_host: 127.0.0.1
_database_host: forms_database
_database_name: forms
_database_user: forms
_database_password: forms
_database_ui_host: ui.database.forms.ds
_api_name: forms
_api_env: prod
_api_secret: ''
_api_host: api.forms.ds
_api_discovery_host: api.discovery.ds
_api_discovery_credential: ~
_api_encryption: ''
_api_system_username: system
_api_system_password: ''
