---
- name: Up tasks container
  docker_service:
      project_src: /srv/tasks
      state: present

- name: Waiting for tasks container to finalize installation
  shell:
      cmd: docker-compose exec -T php pidof php-fpm | cat
      chdir: /srv/tasks
  register: output
  until: output.stdout|match('^[0-9]+(\s[0-9]+)*$')
  retries: 60
  delay: 10
