---
- name: Up tasks container
  shell:
      cmd: docker-compose up -d
      chdir: /srv/tasks
  register: output
  changed_when: output.stderr != 'tasks_tasks_db_1 is up-to-date\ntasks_tasks_php_1 is up-to-date\ntasks_tasks_nginx_1 is up-to-date'
