---
- block:
    - name: Gather information for services container
      include_tasks: /etc/ansible/task/app/proxy/container/info.yml
    - name: Up services container
      include_role:
        name: app/services/container/up
      vars:
        _env: '{{ env }}'
        _compose_project_name: '{{ namespace }}services'
        _network: '{{ namespace }}proxy_default'
        _proxy_host: '{{ proxy_container_info_ip.stdout }}'
        _nginx_virtual_host: '{{ app.services.api.host }}'
        _adminer_virtual_host: '{{ app.services.adminer.host }}'
        _rebrow_virtual_host: '{{ app.services.rebrow.host }}'
        _discovery_host: '{{ app.discovery.api.host }}'
        _directory: '{{ directory }}/services'
        _database_host: '{{ app.services.database.host }}'
        _database_port: '{{ app.services.database.port }}'
        _database_name: '{{ app.services.database.name }}'
        _database_username: '{{ app.services.database.username }}'
        _database_password: '{{ app.services.database.password }}'
  when: app.services.enabled
  tags: [services]
