---
- block:
    - name: Gather information for tenants container
      include_tasks: /etc/ansible/task/app/proxy/container/info.yml
    - name: Detect docker credential file
      local_action: 'stat path=/root/docker/credential'
      register: docker_credential
    - name: Up tenants container
      include_role:
        name: app/tenants/container/up
      vars:
        _env: '{{ env }}'
        _compose_project_name: '{{ namespace }}tenants'
        _network: '{{ namespace }}proxy_default'
        _proxy_host: '{{ proxy_container_info_ip.stdout }}'
        _nginx_virtual_host: '{{ app.tenants.api.host }}'
        _adminer_virtual_host: '{{ app.tenants.adminer.host }}'
        _rebrow_virtual_host: '{{ app.tenants.rebrow.host }}'
        _discovery_host: '{{ app.discovery.api.host }}'
        _directory: '{{ directory }}/tenants'
        _database_host: '{{ app.tenants.database.host }}'
        _database_port: '{{ app.tenants.database.port }}'
        _database_name: '{{ app.tenants.database.name }}'
        _database_username: '{{ app.tenants.database.username }}'
        _database_password: '{{ app.tenants.database.password }}'
        _credential: '{{ lookup("file", "/root/docker/credential") if docker_credential.stat.exists == true else none}}'
  when: app.tenants.enabled
  tags: [tenants]
