---
- block:
    - name: Define tenants encryption variables
      set_fact:
        tenants_encryption_secret: '{{ platform.encryption.secret }}'
    - name: Configure tenants encryption settings
      include_role:
        name: app/tenants/encryption/configure
  when: app.tenants.enabled
  tags: [tenants]
