---
- block:
    - name: Stop tasks container
      docker_service:
        project_src: /srv/tasks
        files: '{{ _files|list }}'
        state: present
        stopped: yes
      environment:
        NETWORK: '{{ _network }}'
        PROXY_HOST: '{{ _proxy_host }}'
  tags: [tasks]
