---
_files: ['docker-compose.yml']
_namespace: ds
_directory: /srv/assets
_network: ds_proxy_default
_proxy_host: 127.0.0.1
_database_host: assets_database
_database_name: assets
_database_user: assets
_database_password: assets
_database_ui_host: ui.database.assets.ds
_api_name: assets
_api_env: prod
_api_secret: ''
_api_host: api.assets.ds
_api_jwt_pass_phrase: ~
_api_discovery_host: api.discovery.ds
_api_discovery_credential: ~
_api_encryption: ~
_api_system_username: system
_api_system_password: ~
