---
- name: Configure proxy host environment variable
  lineinfile:
      path: /srv/formio/.env
      regexp: '^PROXY_HOST='
      line: 'PROXY_HOST={{ proxy_host }}'

- name: Configure formio host environment variable
  lineinfile:
      path: /srv/formio/.env
      regexp: '^VIRTUAL_HOST='
      line: 'VIRTUAL_HOST={{ formio_host }}'
