---
- import_playbook: app/server/initialize.yml
- import_playbook: app/server/setup.yml
- import_playbook: app/container/down.yml
- import_playbook: app/repository/download.yml
- import_playbook: app/repository/override.yml
- import_playbook: app/jwt/key/download.yml
- import_playbook: app/container/up.yml
- import_playbook: app/discovery/config/configure.yml
- import_playbook: app/discovery/configure.yml
- import_playbook: app/encryption/configure.yml
- import_playbook: app/integration/configure.yml
- import_playbook: app/jwt/configure.yml
- import_playbook: app/mail/configure.yml
- import_playbook: app/system/configure.yml
- import_playbook: app/database/migration/load.yml
- import_playbook: app/database/fixtures/load.yml
