---
- import_playbook: app/system/initialize.yml
- import_playbook: app/system/setup.yml
- import_playbook: app/container/down.yml
- import_playbook: app/proxy/container/down.yml
- import_playbook: app/repository/download.yml
- import_playbook: app/repository/override.yml
- import_playbook: app/jwt/key/download.yml
- import_playbook: app/proxy/container/up.yml
- import_playbook: app/container/up.yml
- import_playbook: app/discovery/configure.yml
- import_playbook: app/encryption/configure.yml
- import_playbook: app/jwt/configure.yml
- import_playbook: app/mail/configure.yml
- import_playbook: app/database/migration/load.yml
- import_playbook: app/database/fixtures/load.yml
