---
- name: Up assets container
  docker_service:
      project_src: /srv/assets
      state: present

- name: Waiting for assets container to finalize installation
  shell:
      cmd: docker-compose exec -T php pidof php-fpm | cat
      chdir: /srv/assets
  register: output
  until: output.stdout|match('^[0-9]+(\s[0-9]+)*$')
  retries: 60
  delay: 10
