version: '3.4'

services:
  database_ui:
    environment:
      SERVICE_8080_ID: ${COMPOSE_PROJECT_NAME}_database_ui_http
      SERVICE_8080_NAME: ${COMPOSE_PROJECT_NAME}_database_ui_http
      SERVICE_8080_TAGS: proxy.enable=true,proxy.tags=external,proxy.frontend.entryPoints=http,proxy.frontend.rule=Host:${DATABASE_UI_HOST}
