all:
    hosts:
        server:
            ansible_host: ~
            ansible_port: 22
            ansible_ssh_private_key_file: /root/.ssh/dev/key

    vars:
        documentation: ~
        guide: ~
        api: develop
        assets: develop
        authentication: develop
        camunda: develop
        cases: develop
        cms: develop
        core: ~
        discovery: ~
        formio: develop
        identities: develop
        interactions: ~
        logs: develop
        records: develop
        services: develop
        tasks: ~
        topics: ~
        admin: develop
        monitor: develop
        portal: develop
        ui: ~

        assets_host: api.assets.ds
        authentication_host: api.authentication.ds
        camunda_host: api.camunda.ds
        cases_host: api.cases.ds
        cms_host: api.cms.ds
        discovery_host: api.discovery.ds
        formio_host: api.formio.ds
        identities_host: api.identities.ds
        interactions_host: api.interactions.ds
        logs_host: api.logs.ds
        records_host: api.records.ds
        services_host: api.services.ds
        tasks_host: api.tasks.ds
        topics_host: api.topics.ds

        jwt_private_key: /root/resource/security/jwt/dev/key
        jwt_public_key: /root/resource/security/jwt/dev/key.pub
        jwt_key_pass_phrase: ~

        fixtures: dev
