all:
    hosts:
        sdk:
            ansible_connection: local
        server:
            ansible_host: ~
            ansible_port: 22
            ansible_ssh_private_key_file: /root/.ssh/dev/key
    vars:
        project: ds
        directory: /srv
        env: dev
        timezone: UTC
        jwt:
            private_key: /root/resource/jwt/dev/key
            public_key: /root/resource/jwt/dev/key.pub
            key_pass_phase: ~
        mail:
            transport: smtp
            host: 127.0.0.1
            port: ~
            username: admin@localhost
            password: ~
        fixtures: dev
        user:
            system:
                password: ~
            anonymous:
                password: ~
            admin:
                password: ~
        util:
            adminer: /root/resource/util/adminer.php
        admin:
            enabled: true
            repository: https://github.com/DigitalState/Admin.git
            version: develop
            host: admin.dev.ds
        assets:
            enabled: true
            repository: https://github.com/DigitalState/Assets.git
            version: develop
            host: api.assets.dev.ds
        authentication:
            enabled: true
            repository: https://github.com/DigitalState/Authentication.git
            version: develop
            host: api.authentication.dev.ds
        camunda:
            enabled: true
            repository: https://github.com/DigitalState/Camunda.git
            version: develop
            host: api.camunda.dev.ds
        cases:
            enabled: true
            repository: https://github.com/DigitalState/Cases.git
            version: develop
            host: api.cases.dev.ds
        cms:
            enabled: true
            repository: https://github.com/DigitalState/Cms.git
            version: develop
            host: api.cms.dev.ds
        core:
            enabled: false
            repository: https://github.com/DigitalState/Core.git
            version: develop
        discovery:
            enabled: false
            repository: https://github.com/DigitalState/Discovery.git
            version: develop
            host: api.discovery.dev.ds
        documentation:
            enabled: false
            repository: https://github.com/DigitalState/Documentation.git
            version: master
        formio:
            enabled: true
            repository: https://github.com/DigitalState/Formio.git
            version: develop
            host: api.formio.dev.ds
        guide:
            enabled: false
            repository: https://github.com/DigitalState/Guide.git
            version: master
        identities:
            enabled: true
            repository: https://github.com/DigitalState/Identities.git
            version: develop
            host: api.identities.dev.ds
        interactions:
            enabled: false
            repository: https://github.com/DigitalState/Interactions.git
            version: develop
            host: api.interactions.dev.ds
        logs:
            enabled: false
            repository: https://github.com/DigitalState/Logs.git
            version: develop
            host: api.logs.dev.ds
        monitor:
            enabled: false
            repository: https://github.com/DigitalState/Monitor.git
            version: develop
            host: monitor.dev.ds
        portal:
            enabled: true
            version: develop
            repository: https://github.com/DigitalState/Portal.git
            host: portal.dev.ds
        proxy:
            enabled: true
            repository: https://github.com/DigitalState/Proxy.git
            version: develop
            port: 80
        records:
            enabled: true
            version: develop
            repository: https://github.com/DigitalState/Records.git
            host: api.records.dev.ds
        services:
            enabled: true
            repository: https://github.com/DigitalState/Services.git
            version: develop
            host: api.services.dev.ds
        tasks:
            enabled: false
            repository: https://github.com/DigitalState/Tasks.git
            version: develop
            host: api.tasks.dev.ds
        topics:
            enabled: false
            repository: https://github.com/DigitalState/Topics.git
            version: develop
            host: api.topics.dev.ds
        ui:
            enabled: false
            repository: https://github.com/DigitalState/Ui.git
            version: develop
