---
- block:
      - name: Configure topics namespace environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^COMPOSE_PROJECT_NAME='
            line: 'COMPOSE_PROJECT_NAME={{ topics_compose_project_name }}'
      - name: Configure topics network environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^NETWORK='
            line: 'NETWORK={{ topics_network }}'
      - name: Configure proxy host environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^PROXY_HOST='
            line: 'PROXY_HOST={{ topics_proxy_host }}'
      - name: Configure virtual host environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^VIRTUAL_HOST='
            line: 'VIRTUAL_HOST={{ topics_virtual_host }}'
      - name: Configure discovery host environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^DISCOVERY_HOST='
            line: 'DISCOVERY_HOST={{ topics_discovery_host }}'
      - name: Configure directory environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^DIRECTORY='
            line: 'DIRECTORY={{ topics_directory }}'
      - name: Configure jwt private key environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^JWT_PRIVATE_KEY='
            line: 'JWT_PRIVATE_KEY={{ topics_jwt_private_key }}'
      - name: Configure jwt public key environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^JWT_PUBLIC_KEY='
            line: 'JWT_PUBLIC_KEY={{ topics_jwt_public_key }}'
      - name: Configure database host environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^DATABASE_HOST='
            line: 'DATABASE_HOST={{ topics_database_host }}'
      - name: Configure database port environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^DATABASE_PORT='
            line: 'DATABASE_PORT={{ topics_database_port }}'
      - name: Configure database name environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^DATABASE_NAME='
            line: 'DATABASE_NAME={{ topics_database_name }}'
      - name: Configure database username environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^DATABASE_USERNAME='
            line: 'DATABASE_USERNAME={{ topics_database_username }}'
      - name: Configure database password environment variable
        lineinfile:
            create: yes
            path: '/srv/topics/{{ topics_env_file }}'
            regexp: '^DATABASE_PASSWORD='
            line: 'DATABASE_PASSWORD={{ topics_database_password }}'
  when: topics_env_file is not none

- name: Up topics container
  docker_service:
      project_src: /srv/topics
      state: present
  environment:
      COMPOSE_PROJECT_NAME: '{{ topics_compose_project_name }}'
      NETWORK: '{{ topics_network }}'
      PROXY_HOST: '{{ topics_proxy_host }}'
      VIRTUAL_HOST: '{{ topics_virtual_host }}'
      DIRECTORY: '{{ topics_directory }}'
      JWT_PRIVATE_KEY: '{{ topics_jwt_private_key }}'
      JWT_PUBLIC_KEY: '{{ topics_jwt_public_key }}'
      DATABASE_HOST: '{{ topics_database_host }}'
      DATABASE_PORT: '{{ topics_database_port }}'
      DATABASE_NAME: '{{ topics_database_name }}'
      DATABASE_USERNAME: '{{ topics_database_username }}'
      DATABASE_PASSWORD: '{{ topics_database_password }}'

- name: Waiting for topics container to finalize installation
  shell:
      cmd: docker-compose exec -T php pidof php-fpm | cat
      chdir: /srv/topics
  register: output
  until: output.stdout|match('^[0-9]+(\s[0-9]+)*$')
  retries: 60
  delay: 10
