---
- block:
    - name: Up camunda container
      docker_service:
        project_src: /srv/camunda
        files:
          - docker-compose.yml
          - 'docker-compose.{{ _env }}.yml'
        state: present
        debug: no
      environment:
        COMPOSE_PROJECT_NAME: '{{ _compose_project_name }}'
        NETWORK: '{{ _network }}'
        JAVA_OPTS: '-Djava.security.egd=file:/dev/./urandom -Duser.timezone={{ _timezone }}'
        PROXY_HOST: '{{ _proxy_host }}'
        VIRTUAL_HOST: '{{ _virtual_host }}'
        DIRECTORY: '{{ _directory }}'
        USERNAME: '{{ _username }}'
        PASSWORD: '{{ _password }}'
  tags: [camunda]
