---
cases_env_file: ~
cases_compose_project_name: ds_cases
cases_network: ds_default
cases_proxy_host: 127.0.0.1
cases_virtual_host: api.cases.ds
cases_directory: /srv/cases
cases_jwt_private_key: ./var/jwt/key
cases_jwt_public_key: ./var/jwt/key.pub
cases_database_host: cases_db
cases_database_port: 3306
cases_database_name: cases
cases_database_username: cases
cases_database_password: cases
