---
- block:
    - name: Load cases database fixture
      shell:
        cmd: 'docker-compose exec -T -e FIXTURES={{ _fixture }} php php bin/console doctrine:fixtures:load --no-interaction'
        chdir: /srv/cases
    - name: Pause while cases fixture load
      pause:
        seconds: 15
  tags: [cases]
