---
- name: Set authentication config
  shell:
      cmd: 'docker-compose exec php php bin/console ds:config:set {{ item.key }} {{ item.value }} | cat'
      chdir: /srv/authentication
  with_dict: '{{ config }}'
