---
assets:
  enabled: true
  repository: https://github.com/DigitalState/Assets.git
  version: feature/apip-2-3-3-upgrade
  api:
    host: api.assets.dev.ds
  database:
    host: assets_database
    name: assets
    user: assets
    password: assets
    ui:
      host: ui.database.assets.dev.ds
  mock:
    discovery:
      host: discovery.mock.assets.dev.ds
  docker:
    - docker-compose.yml
    - docker-compose.dev.yml
    - /root/docker/assets/docker-compose.yml
    - /root/docker/assets/docker-compose.dev.yml
    - /root/docker/api.dev.yml
    - /root/docker/php.dev.yml
