---
authentication:
  enabled: true
  repository: https://github.com/DigitalState/Authentication.git
  version: feature/apip-2-3-3-upgrade
  api:
    host: api.authentication.dev.ds
  database:
    host: authentication_database
    name: authentication
    user: authentication
    password: authentication
    ui:
      host: ui.database.authentication.dev.ds
  mock:
    discovery:
      host: discovery.mock.authentication.dev.ds
  docker:
    - docker-compose.yml
    - docker-compose.dev.yml
    - /root/docker/authentication/docker-compose.yml
    - /root/docker/authentication/docker-compose.dev.yml
    - /root/docker/api.dev.yml
    - /root/docker/php.dev.yml
