---
cases:
  enabled: true
  repository: https://github.com/DigitalState/Cases.git
  version: feature/apip-2-3-3-upgrade
  api:
    host: api.cases.dev.ds
  database:
    host: cases_database
    name: cases
    user: cases
    password: cases
    ui:
      host: ui.database.cases.dev.ds
  mock:
    discovery:
      host: discovery.mock.cases.dev.ds
  docker:
    - docker-compose.yml
    - docker-compose.dev.yml
    - /root/docker/cases/docker-compose.yml
    - /root/docker/cases/docker-compose.dev.yml
    - /root/docker/api.dev.yml
    - /root/docker/php.dev.yml
