---
formio:
  enabled: true
  order: -10
  repository: https://github.com/DigitalState/Formio.git
  version: 0.14.0
  api:
    host: api.formio.dev.ds
  database:
    ui:
      host: adminer.formio.dev.ds
  username: admin@staff.ds
  password: admin
