---
forms:
  enabled: true
  repository: https://github.com/DigitalState/Forms.git
  version: feature/apip-2-3-3-upgrade
  api:
    host: api.forms.dev.ds
  database:
    host: forms_database
    name: forms
    user: forms
    password: forms
    ui:
      host: ui.database.forms.dev.ds
  mock:
    discovery:
      host: discovery.mock.forms.dev.ds
  docker:
    - docker-compose.yml
    - docker-compose.dev.yml
    - /root/docker/forms/docker-compose.yml
    - /root/docker/forms/docker-compose.dev.yml
    - /root/docker/api.dev.yml
    - /root/docker/php.dev.yml
