---
interactions:
  enabled: false
  repository: https://github.com/DigitalState/Interactions.git
  version: 0.10.0
  api:
    host: api.interactions.dev.ds
  database:
    host: interactions_database
    port: 5432
    name: interactions
    username: interactions
    password: interactions
    ui:
      host: ui.database.interactions.dev.ds
  cache:
    ui:
      host: ui.cache.interactions.dev.ds
