---
records:
  enabled: true
  repository: https://github.com/DigitalState/Records.git
  version: feature/apip-2-3-3-upgrade
  api:
    host: api.records.dev.ds
  database:
    host: records_database
    name: records
    user: records
    password: records
    ui:
      host: ui.database.records.dev.ds
  mock:
    discovery:
      host: discovery.mock.records.dev.ds
  docker:
    - docker-compose.yml
    - docker-compose.dev.yml
    - /root/docker/records/docker-compose.yml
    - /root/docker/records/docker-compose.dev.yml
    - /root/docker/api.dev.yml
    - /root/docker/php.dev.yml
