---
tasks:
  enabled: false
  repository: https://github.com/DigitalState/Tasks.git
  version: 0.12.0
  api:
    host: api.tasks.dev.ds
  database:
    host: tasks_database
    port: 5432
    name: tasks
    username: tasks
    password: tasks
    ui:
      host: ui.database.tasks.dev.ds
  cache:
    ui:
      host: ui.cache.tasks.dev.ds
