---
tasks:
  enabled: true
  repository: https://github.com/DigitalState/Tasks.git
  version: feature/apip-2-3-3-upgrade
  api:
    host: api.tasks.dev.ds
  database:
    host: tasks_database
    name: tasks
    user: tasks
    password: tasks
    ui:
      host: ui.database.tasks.dev.ds
  mock:
    discovery:
      host: discovery.mock.tasks.dev.ds
  docker:
    - docker-compose.yml
    - docker-compose.dev.yml
    - /root/docker/tasks/docker-compose.yml
    - /root/docker/tasks/docker-compose.dev.yml
    - /root/docker/api.dev.yml
    - /root/docker/php.dev.yml
