---
tenants:
  enabled: false
  repository: https://github.com/DigitalState/Tenants.git
  version: 0.10.0
  api:
    host: api.tenants.dev.ds
  database:
    host: tenants_database
    port: 5432
    name: tenants
    username: tenants
    password: tenants
    ui:
      host: ui.database.tenants.dev.ds
  cache:
    ui:
      host: ui.cache.tenants.dev.ds
