---
topics:
  enabled: false
  repository: https://github.com/DigitalState/Topics.git
  version: 0.12.0
  api:
    host: api.topics.dev.ds
  database:
    host: topics_database
    port: 5432
    name: topics
    username: topics
    password: topics
    ui:
      host: ui.database.topics.dev.ds
  cache:
    ui:
      host: ui.cache.topics.dev.ds
