---
- block:
    - name: Run identities health check
      include_role:
        name: app/identities/health/run
    - name: Validate identities health check result
      debug:
        msg: '{{ "Healthy" if (_result.stdout|from_json).healthy else "Not Health" }}'
      failed_when: (_result.stdout|from_json).healthy != true
  tags: [identities]
