---
- block:
    - name: Define cms jwt variables
      set_fact:
        cms_jwt_key_pass_phrase: '{{ jwt.pass_phrase }}'
    - name: Configure cms jwt key pass phrase
      include_role:
        name: app/cms/jwt/configure
  when: app.cms.enabled
  tags: [cms]
