---
tasks_env_file: ~
tasks_compose_project_name: ds_tasks
tasks_network: ds_default
tasks_proxy_host: 127.0.0.1
tasks_virtual_host: api.tasks.ds
tasks_discovery_host: api.discovery.ds
tasks_directory: /srv/tasks
tasks_jwt_private_key: ./var/jwt/key
tasks_jwt_public_key: ./var/jwt/key.pub
tasks_database_host: tasks_db
tasks_database_port: 5432
tasks_database_name: tasks
tasks_database_username: tasks
tasks_database_password: tasks
tasks_credential: ~
