---
assets_compose_project_name: ds_assets
assets_network: ds_default
assets_proxy_host: 127.0.0.1
assets_virtual_host: api.assets.ds
assets_directory: /srv/assets
assets_jwt_private_key: ./var/jwt/key
assets_jwt_public_key: ./var/jwt/key.pub
