---
assets_env_file: ~
assets_compose_project_name: ds_assets
assets_network: ds_default
assets_proxy_host: 127.0.0.1
assets_virtual_host: api.assets.ds
assets_directory: /srv/assets
assets_jwt_private_key: ./var/jwt/key
assets_jwt_public_key: ./var/jwt/key.pub
assets_database_host: assets_db
assets_database_port: 5432
assets_database_name: assets
assets_database_username: assets
assets_database_password: assets
