---
- name: Compile repository list
  hosts: platform
  become: true
  tasks:
    - name: ...
      include_tasks: /etc/ansible/task/platform/compiler/repository/download.yml
  tags: [always]

- name: Download repositories
  hosts: server
  become: true
  tasks:
    - name: Include compiled task list
      include_tasks: '{{ file }}'
      with_items: '{{ hostvars["platform"]["_files"] }}'
      loop_control:
        loop_var: file
