---
- block:
    - name: Stop portal container
      docker_service:
        project_src: /srv/portal
        files:
          - docker-compose.yml
          - 'docker-compose.{{ portal_env }}.yml'
        state: present
        stopped: yes
  tags: [portal]
