---
- block:
    - name: Load tenants database fixture
      shell:
        cmd: 'docker-compose exec -T -e FIXTURES={{ _fixture }} php php bin/console doctrine:fixtures:load --no-interaction'
        chdir: /srv/tenants
    - name: Pause while tenants fixture load
      pause:
        seconds: 15
  tags: [tenants]
