---
- block:
    - name: Gather information for camunda container
      include_tasks: /etc/ansible/task/app/proxy/container/info.yml
    - name: Up camunda container
      include_role:
        name: app/camunda/container/up
      vars:
        _env: '{{ env }}'
        _compose_project_name: '{{ namespace }}camunda'
        _network: '{{ namespace }}proxy_default'
        _proxy_host: '{{ proxy_container_info_ip.stdout }}'
        _virtual_host: '{{ app.camunda.api.host }}'
        _discovery_host: '{{ app.discovery.api.host }}'
        _directory: '{{ directory }}/camunda'
        _timezone: '{{ timezone }}'
        _username: '{{ app.camunda.username }}'
        _password: '{{ app.camunda.password }}'
  when: app.camunda.enabled
  tags: [camunda]
