---
- block:
    - name: Create identities repository tag
      include_role:
        name: app/identities/repository/tag/create
      vars:
        _repository: '{{ app.identities.repository }}'
        _tag: '{{ tag }}'
  when: app.identities.enabled
  tags: [identities]
