---
- block:
    - name: Configure interactions system username setting
      lineinfile:
        path: '/srv/interactions/app/config/parameters.yml'
        regexp: '^\s{4}system_username:'
        line: '    system_username: {{ _username }}'
    - name: Configure interactions mail password setting
      lineinfile:
        path: '/srv/interactions/app/config/parameters.yml'
        regexp: '^\s{4}system_password:'
        line: '    system_password: ''{{ _password }}'''
  tags: [interactions]
