---
- block:
    - name: Define assets jwt variables
      set_fact:
        assets_jwt_key_pass_phrase: '{{ platform.jwt.pass_phrase }}'
    - name: Configure assets jwt key pass phrase
      include_role:
        name: app/assets/jwt/configure
  when: app.assets.enabled
  tags: [assets]
