---
- name: ...
  include_tasks: /etc/ansible/task/platform/compiler/find.yml
  vars:
      tag: jwt

- name: ...
  set_fact:
      _files: []

- name: ...
  include_tasks: /etc/ansible/task/platform/compiler/item.yml
  vars:
      tag: jwt
      task: configure
  with_items: '{{ _items }}'
  when: vars[item|basename].enabled

- name: Completed
  debug:
      msg: Jwt list has been compiled.
