---
_files: ['docker-compose.yml']
_namespace: ds
_directory: /srv/tasks
_network: ds_proxy_default
_proxy_host: 127.0.0.1
_database_host: tasks_database
_database_name: tasks
_database_user: tasks
_database_password: ~
_database_ui_host: ui.database.tasks.ds
_api_name: tasks
_api_env: prod
_api_secret: ''
_api_host: api.tasks.ds
_api_jwt_pass_phrase: ~
_api_discovery_adapter: consul
_api_discovery_consul_host: api.discovery.ds
_api_discovery_consul_credentials: ~
_api_discovery_env_services: ~
_api_discovery_env_configs: ~
_api_encryption: ~
_api_system_username: system
_api_system_password: ~
_mock_discovery_host: discovery.mock.tasks.ds
