---
- block:
    - name: Define services encryption variables
      set_fact:
        services_encryption_secret: '{{ encryption.secret }}'
    - name: Configure services encryption settings
      include_role:
        name: app/services/encryption/configure
  when: app.services.enabled
  tags: [services]
