---
- block:
    - name: Down discovery container
      docker_service:
        project_src: /srv/discovery
        files:
          - docker-compose.yml
          - 'docker-compose.{{ discovery_env }}.yml'
        state: absent
        remove_volumes: '{{ "no" if discovery_persistent else "yes" }}'
  tags: [discovery]
