---
- block:
    - name: Up interactions container
      docker_service:
        project_src: /srv/interactions
        files:
          - docker-compose.yml
          - 'docker-compose.{{ _env }}.yml'
        state: present
      environment:
        COMPOSE_PROJECT_NAME: '{{ _compose_project_name }}'
        NETWORK: '{{ _network }}'
        PROXY_HOST: '{{ _proxy_host }}'
        NGINX_VIRTUAL_HOST: '{{ _nginx_virtual_host }}'
        ADMINER_VIRTUAL_HOST: '{{ _adminer_virtual_host }}'
        REBROW_VIRTUAL_HOST: '{{ _rebrow_virtual_host }}'
        DIRECTORY: '{{ _directory }}'
        DATABASE_HOST: '{{ _database_host }}'
        DATABASE_PORT: '{{ _database_port }}'
        DATABASE_NAME: '{{ _database_name }}'
        DATABASE_USERNAME: '{{ _database_username }}'
        DATABASE_PASSWORD: '{{ _database_password }}'
    - name: Waiting for interactions container to finalize installation
      shell:
        cmd: docker-compose exec -T php pidof php-fpm | cat
        chdir: /srv/interactions
      register: _output
      until: _output.stdout is match('^[0-9]+(\s[0-9]+)*$')
      retries: 60
      delay: 10
  tags: [interactions]
