---
- name: Up topics container
  shell: 'docker-compose -f /srv/service/topics/docker-compose.yml up -d'
  register: output
  changed_when: output.stderr != 'topics_db_1 is up-to-date\nStarting topics_php_1 ... \r\nStarting topics_php_1\n\u001b[1A\u001b[2K\rStarting %s_php_1 ... \u001b[32mdone\u001b[0m\r\u001b[1B%s_nginx_1 is up-to-date'
