---
- name: Set tasks config
  shell:
      cmd: 'docker-compose exec tasks_php bin/console ds:config:set {{ item.key }} {{ item.value }} | cat'
      chdir: /srv/service/tasks
  with_dict: '{{ config }}'
