---
- block:
      - name: Gather information for admin container
        include_tasks: /etc/ansible/task/app/proxy/container/info.yml
      - name: Define admin container variables
        set_fact:
            admin_env_file: .env.lab
        when: env == 'lab'
      - name: Define admin container variables
        set_fact:
            admin_discovery: {}
      - name: Append each enabled services to the discovery environment variable
        set_fact:
            admin_discovery: '{{ admin_discovery|combine({item: {"host": vars[item].host}}) }}'
        with_items:
            - admin
            - assets
            - authentication
            - camunda
            - cases
            - cms
            - discovery
            - formio
            - identities
            - interactions
            - logs
            - monitor
            - portal
            - records
            - services
            - tasks
            - topics
      - name: Define admin container variables
        set_fact:
            admin_namespace: '{{ project }}_admin'
            admin_network: '{{ project }}_default'
            admin_proxy_host: '{{ proxy_container_info_ip.stdout }}'
            admin_virtual_host: '{{ admin.host }}'
            admin_directory: '{{ directory }}/admin'
      - name: Up admin container
        include_role:
            name: app/admin/container/up
  when: admin.enabled
  tags: [admin]
