---
- name: Up containers on server
  hosts: server
  become: true
  roles:
    - service/assets/container/up
    - service/authentication/container/up
    - service/camunda/container/up
    - service/cases/container/up
    - service/cms/container/up
    - service/formio/container/up
    - service/identities/container/up
    - service/records/container/up
    - service/services/container/up
    - { role: service/tasks/container/up, when: edition == 'enterprise' }
    - spa/admin/container/up
    - spa/portal/container/up
