---
- block:
      - name: Configure cms namespace environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^COMPOSE_PROJECT_NAME='
            line: 'COMPOSE_PROJECT_NAME={{ cms_compose_project_name }}'
      - name: Configure cms network environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^NETWORK='
            line: 'NETWORK={{ cms_network }}'
      - name: Configure proxy host environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^PROXY_HOST='
            line: 'PROXY_HOST={{ cms_proxy_host }}'
      - name: Configure virtual host environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^VIRTUAL_HOST='
            line: 'VIRTUAL_HOST={{ cms_virtual_host }}'
      - name: Configure discovery host environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^DISCOVERY_HOST='
            line: 'DISCOVERY_HOST={{ cms_discovery_host }}'
      - name: Configure directory environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^DIRECTORY='
            line: 'DIRECTORY={{ cms_directory }}'
      - name: Configure jwt private key environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^JWT_PRIVATE_KEY='
            line: 'JWT_PRIVATE_KEY={{ cms_jwt_private_key }}'
      - name: Configure jwt public key environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^JWT_PUBLIC_KEY='
            line: 'JWT_PUBLIC_KEY={{ cms_jwt_public_key }}'
      - name: Configure database host environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^DATABASE_HOST='
            line: 'DATABASE_HOST={{ cms_database_host }}'
      - name: Configure database port environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^DATABASE_PORT='
            line: 'DATABASE_PORT={{ cms_database_port }}'
      - name: Configure database name environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^DATABASE_NAME='
            line: 'DATABASE_NAME={{ cms_database_name }}'
      - name: Configure database username environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^DATABASE_USERNAME='
            line: 'DATABASE_USERNAME={{ cms_database_username }}'
      - name: Configure database password environment variable
        lineinfile:
            create: yes
            path: '/srv/cms/{{ cms_env_file }}'
            regexp: '^DATABASE_PASSWORD='
            line: 'DATABASE_PASSWORD={{ cms_database_password }}'
  when: cms_env_file is not none

- name: Up cms container
  docker_service:
      project_src: /srv/cms
      state: present
  environment:
      COMPOSE_PROJECT_NAME: '{{ cms_compose_project_name }}'
      NETWORK: '{{ cms_network }}'
      PROXY_HOST: '{{ cms_proxy_host }}'
      VIRTUAL_HOST: '{{ cms_virtual_host }}'
      DIRECTORY: '{{ cms_directory }}'
      JWT_PRIVATE_KEY: '{{ cms_jwt_private_key }}'
      JWT_PUBLIC_KEY: '{{ cms_jwt_public_key }}'
      DATABASE_HOST: '{{ cms_database_host }}'
      DATABASE_PORT: '{{ cms_database_port }}'
      DATABASE_NAME: '{{ cms_database_name }}'
      DATABASE_USERNAME: '{{ cms_database_username }}'
      DATABASE_PASSWORD: '{{ cms_database_password }}'

- name: Waiting for cms container to finalize installation
  shell:
      cmd: docker-compose exec -T php pidof php-fpm | cat
      chdir: /srv/cms
  register: output
  until: output.stdout|match('^[0-9]+(\s[0-9]+)*$')
  retries: 60
  delay: 10
