---
- block:
    - name: Gather information for interactions container
      include_tasks: /etc/ansible/task/app/proxy/container/info.yml
    - name: Up interactions container
      include_role:
        name: app/interactions/container/up
      vars:
        _env: '{{ env }}'
        _compose_project_name: '{{ namespace }}interactions'
        _network: '{{ namespace }}proxy_default'
        _proxy_host: '{{ proxy_container_info_ip.stdout }}'
        _nginx_virtual_host: '{{ app.interactions.api.host }}'
        _adminer_virtual_host: '{{ app.interactions.adminer.host }}'
        _rebrow_virtual_host: '{{ app.interactions.rebrow.host }}'
        _discovery_host: '{{ app.discovery.api.host }}'
        _directory: '{{ directory }}/interactions'
        _database_host: '{{ app.interactions.database.host }}'
        _database_port: '{{ app.interactions.database.port }}'
        _database_name: '{{ app.interactions.database.name }}'
        _database_username: '{{ app.interactions.database.username }}'
        _database_password: '{{ app.interactions.database.password }}'
  when: app.interactions.enabled
  tags: [interactions]
