---
- name: Detect admin repository override directory
  local_action: 'stat path={{ admin_repository_override }}'
  register: repository_override

- name: Download admin repository override directory
  copy:
      src: '{{ admin_repository_override }}/'
      dest: /srv/admin
  when: repository_override.stat.exists == true
