---
- block:
    - name: Down services container
      docker_service:
        project_src: /srv/services
        files:
          - docker-compose.yml
          - 'docker-compose.{{ services_env }}.yml'
        state: absent
        remove_volumes: '{{ "no" if services_persistent else "yes" }}'
  tags: [services]
