---
- block:
    - name: Retrieve proxy container gateway
      include_tasks: /etc/ansible/task/app/proxy/container/property/gateway.yml
    - name: Configure microservice dns
      include_role:
        name: app/dns/configure
      vars:
        _dns:
          - host: '{{ app.microservice.api.host }}'
            ip: '{{ proxy_container_gateway.stdout }}'
  when: app.microservice.enabled
  tags: [microservice]
