---
topics_env_file: ~
topics_compose_project_name: ds_topics
topics_network: ds_default
topics_proxy_host: 127.0.0.1
topics_virtual_host: api.topics.ds
topics_directory: /srv/topics
topics_jwt_private_key: ./var/jwt/key
topics_jwt_public_key: ./var/jwt/key.pub
