---
topics_env_file: ~
topics_compose_project_name: ds_topics
topics_network: ds_default
topics_proxy_host: 127.0.0.1
topics_nginx_virtual_host: api.topics.ds
topics_adminer_virtual_host: api.adminer.ds
topics_discovery_host: api.discovery.ds
topics_directory: /srv/topics
topics_jwt_private_key: ./var/jwt/key
topics_jwt_public_key: ./var/jwt/key.pub
topics_database_host: topics_db
topics_database_port: 5432
topics_database_name: topics
topics_database_username: topics
topics_database_password: topics
