---
camunda_env_file: ~
camunda_compose_project_name: ds_camunda
camunda_network: ds_default
camunda_image_tag: master
camunda_timezone: UTC
camunda_proxy_host: 127.0.0.1
camunda_virtual_host: api.camunda.ds
camunda_discovery_host: api.discovery.ds
camunda_directory: /srv/camunda
camunda_username: admin
camunda_password: admin
