---
- import_playbook: setup/dependencies.yml
- import_playbook: setup/packages.yml
- import_playbook: repository/download.yml
- import_playbook: jwt/download.yml
- import_playbook: container/env/configure.yml
- import_playbook: container/up.yml
- import_playbook: jwt/configure.yml
- import_playbook: database/migrate.yml
- import_playbook: database/fixtures.yml
- import_playbook: config/configure.yml
