all:
    hosts:
        server:
            ansible_host: ~
            ansible_port: 22
            ansible_ssh_private_key_file: /root/.ssh/stag/key

    vars:
        documentation: ~
        guide: ~
        api: master
        assets: master
        authentication: master
        camunda: master
        cases: master
        cms: master
        core: ~
        discovery: master
        formio: master
        identities: master
        interactions: master
        logs: master
        records: master
        services: master
        tasks: master
        topics: master
        admin: master
        monitor: master
        portal: master
        ui: ~

        jwt_private_key: /root/resource/security/jwt/stag/key
        jwt_public_key: /root/resource/security/jwt/stag/key.pub
        jwt_key_pass_phrase: ~

        fixtures: dev
