all:
    hosts:
        server:
            ansible_host: ~
            ansible_port: 22
            ansible_ssh_private_key_file: /root/.ssh/stag/key

    vars:
        ### General ###########################################################

        env: stag

        directory: /srv

        jwt_private_key: /root/resource/jwt/stag/key
        jwt_public_key: /root/resource/jwt/stag/key.pub
        jwt_key_pass_phrase: ~

        data: dev

        ### Documentation #####################################################

        documentation: ~
        documentation_version: master

        ### Guide #############################################################

        guide: ~
        guide_version: master

        ### Proxy #############################################################

        proxy: enabled
        proxy_version: develop

        ### Assets ############################################################

        assets: ~
        assets_version: develop
        assets_host: api.assets.ds

        ### Authentication ####################################################

        authentication: enabled
        authentication_version: develop
        authentication_host: api.authentication.ds

        ### Camunda ###########################################################

        camunda: ~
        camunda_version: develop
        camunda_host: api.camunda.ds

        ### Cases #############################################################

        cases: ~
        cases_version: develop
        cases_host: api.cases.ds

        ### Cms ###############################################################

        cms: ~
        cms_version: develop
        cms_host: api.cms.ds

        ### Discovery #########################################################

        discovery: ~
        discovery_version: develop
        discovery_host: api.discovery.ds

        ### Formio ############################################################

        formio: ~
        formio_version: develop
        formio_host: api.formio.ds

        ### Identities ########################################################

        identities: enabled
        identities_version: develop
        identities_host: api.identities.ds

        ### Interactions ######################################################

        interactions: ~
        interactions_version: develop
        interactions_host: api.interactions.ds

        ### Logs ##############################################################

        logs: ~
        logs_version: develop
        logs_host: api.logs.ds

        ### Records ###########################################################

        records: ~
        records_version: develop
        records_host: api.records.ds

        ### Services ##########################################################

        services: ~
        services_version: develop
        services_host: api.services.ds

        ### Tasks #############################################################

        tasks: ~
        tasks_version: develop
        tasks_host: api.tasks.ds

        ### Topics ############################################################

        topics: ~
        topics_version: develop
        topics_host: api.topics.ds

        ### Core ##############################################################

        core: ~
        core_version: develop

        ### Admin #############################################################

        admin: ~
        admin_version: develop

        ### Monitor ###########################################################

        monitor: ~
        monitor_version: develop

        ### Portal ############################################################

        portal: ~
        portal_version: develop

        ### Ui ################################################################

        ui: ~
        ui_version: develop
