---
- block:
    - name: Stop monitor container
      docker_service:
        project_src: /srv/monitor
        files:
          - docker-compose.yml
          - 'docker-compose.{{ monitor_env }}.yml'
        state: present
        stopped: yes
  tags: [monitor]
