---
- name: Compile database/migration/load task list
  hosts: platform
  become: true
  tasks:
    - name: Compile files
      compile:
        app: '{{ app }}'
        directory: /etc/ansible/task/app/*
        task: database/migration/load
      register: _result
  tags: [always]

- name: Define database migration data
  hosts: server
  become: true
  tasks:
    - set_fact:
        database_migration_data:
          1.0.0:
            tenant:
              uuid: '{{ (ansible_date_time.iso8601_micro + "1")|to_uuid }}'
              title:
                en: Tenant
            user:
              system:
                uuid: '{{ (ansible_date_time.iso8601_micro + "2")|to_uuid }}'
                password: '{{ user.system.password }}'
              anonymous:
                uuid: '{{ (ansible_date_time.iso8601_micro + "3")|to_uuid }}'
                password: '{{ user.anonymous.password }}'
              admin:
                uuid: '{{ (ansible_date_time.iso8601_micro + "4")|to_uuid }}'
                password: '{{ user.admin.password }}'
            identity:
              system:
                uuid: '{{ (ansible_date_time.iso8601_micro + "5")|to_uuid }}'
              admin:
                uuid: '{{ (ansible_date_time.iso8601_micro + "6")|to_uuid }}'
            business_unit:
              administration:
                uuid: '{{ (ansible_date_time.iso8601_micro + "7")|to_uuid }}'
              backoffice:
                uuid: '{{ (ansible_date_time.iso8601_micro + "8")|to_uuid }}'
              portal:
                uuid: '{{ (ansible_date_time.iso8601_micro + "9")|to_uuid }}'
            config:
              app.spa.admin:
                value: 'http://{{ app.admin.host }}'
              app.spa.portal:
                value: 'http://{{ app.portal.host }}'
      tags: [always]

- name: Load database migration
  hosts: server
  become: true
  tasks:
    - name: Include compiled task list
      include_tasks: '{{ _file }}'
      with_items: '{{ hostvars["platform"]["_result"]["tasks"] }}'
      loop_control:
        loop_var: _file
      tags: [always]
