---
- import_playbook: /etc/ansible/playbook/platform/vars/include.yml

- name: Compile database/migration/load task list
  hosts: platform
  become: true
  tasks:
    - name: Compile files
      compile:
        app: '{{ app }}'
        directory: /etc/ansible/task/app/*
        task: database/migration/load
      register: files
  tags: [always]

- name: Define database migration data
  hosts: app
  become: true
  tasks:
    - set_fact:
        data:
          1.0.0:
            tenant:
              uuid: '{{ (ansible_date_time.iso8601_micro + "1")|to_uuid }}'
              title:
                en: Tenant
            system:
              username: '{{ system.username }}'
              password: '{{ system.password }}'
            user:
              system:
                uuid: '{{ (ansible_date_time.iso8601_micro + "2")|to_uuid }}'
                username: '{{ user.system.username }}'
                password: '{{ user.system.password }}'
              anonymous:
                uuid: '{{ (ansible_date_time.iso8601_micro + "3")|to_uuid }}'
                username: '{{ user.anonymous.username }}'
                password: '{{ user.anonymous.password }}'
              admin:
                uuid: '{{ (ansible_date_time.iso8601_micro + "4")|to_uuid }}'
                username: '{{ user.admin.username }}'
                password: '{{ user.admin.password }}'
            identity:
              system:
                uuid: '{{ (ansible_date_time.iso8601_micro + "5")|to_uuid }}'
              admin:
                uuid: '{{ (ansible_date_time.iso8601_micro + "6")|to_uuid }}'
            business_unit:
              administration:
                uuid: '{{ (ansible_date_time.iso8601_micro + "7")|to_uuid }}'
              backoffice:
                uuid: '{{ (ansible_date_time.iso8601_micro + "8")|to_uuid }}'
              portal:
                uuid: '{{ (ansible_date_time.iso8601_micro + "9")|to_uuid }}'
            config:
              app.spa.admin:
                value: 'http://{{ app.admin.ui.host }}'
              app.spa.portal:
                value: 'http://{{ app.portal.ui.host }}'
              app.spa.portal.oauth.success:
                value: 'http://{{ app.portal.ui.host }}/oauth/success'
      tags: [always]

- name: Load database migration
  hosts: app
  become: true
  tasks:
    - name: Include compiled task list
      include_tasks: '{{ item }}'
      with_items: '{{ hostvars["platform"]["files"]["tasks"] }}'
      tags: [always]
