---
- block:
    - name: Define cases encryption variables
      set_fact:
        cases_encryption_secret: '{{ encryption.secret }}'
    - name: Configure cases encryption settings
      include_role:
        name: app/cases/encryption/configure
  when: app.cases.enabled
  tags: [cases]
