---
- import_playbook: /etc/ansible/playbook/platform/vars/include.yml

- name: Install ssh keys
  hosts: platform
  become: true
  gather_facts: false
  tasks:
    - name: Establish ssh connection
      include_role:
        name: platform/ssh/connect
      vars:
        _directory: '{{ env|replace(".", "/") }}'
        _host: '{{ vars["hostvars"]["app"]["ansible_host"] }}'
        _username: root
      when: hostvars.app.ansible_connection is not defined
  tags: [system]

- name: Install ansible requirements
  hosts: app
  become: true
  gather_facts: false
  tasks:
    - name: Install python packages
      include_role:
        name: package/python
      when: hostvars.app.ansible_connection is not defined
  tags: [system]
