---
- block:
    - name: Down cms container
      docker_service:
        project_src: /srv/cms
        files:
          - docker-compose.yml
          - 'docker-compose.{{ cms_env }}.yml'
        state: absent
        remove_volumes: '{{ "no" if cms_persistent else "yes" }}'
  tags: [cms]
