---
- block:
    - name: Download interactions jwt keys
      include_role:
        name: app/interactions/jwt/key/download
      vars:
        _private_key: '/root/resource/jwt/{{ env|replace(".", "/") }}/key'
        _public_key: '/root/resource/jwt/{{ env|replace(".", "/") }}/key.pub'
  when: app.interactions.enabled
  tags: [interactions]
