---
- block:
    - name: Download records jwt keys
      include_role:
        name: app/records/jwt/key/download
      vars:
        _private_key: '/root/resource/jwt/{{ env|replace(".", "/") }}/key'
        _public_key: '/root/resource/jwt/{{ env|replace(".", "/") }}/key.pub'
  when: app.records.enabled
  tags: [records]
