---
- name: Compile jwt list
  hosts: platform
  become: true
  tasks:
      - name: ...
        include_tasks: /etc/ansible/task/platform/compiler/jwt/configure.yml
  tags: [always]

- name: Configure jwt key pass phrases
  hosts: server
  become: true
  tasks:
      - name: Include compiled list
        include_tasks: '{{ file }}'
        with_items: '{{ hostvars["platform"]["files"] }}'
        loop_control:
            loop_var: file
