all:
    hosts:
        sdk:
            ansible_connection: local
        server:
            ansible_connection: local
    vars:
        project: ds
        directory: ~
        env: lab
        timezone: UTC
        encryption:
            secret: ~
        jwt:
            private_key: /root/resource/jwt/lab/key
            public_key: /root/resource/jwt/lab/key.pub
            key_pass_phrase: ~
        mail:
            transport: smtp
            host: 127.0.0.1
            port: ~
            username: mail@localhost
            password: ~
        fixtures: dev
        user:
            system:
                password: system
            anonymous:
                password: anonymous
            admin:
                password: admin
        admin:
            enabled: true
            repository: https://github.com/DigitalState/Admin.git
            version: 0.1.6
            host: admin.lab.ds
        assets:
            enabled: true
            repository: https://github.com/DigitalState/Assets.git
            version: 0.2.3
            api:
                host: api.assets.lab.ds
            adminer:
                host: adminer.assets.lab.ds
            database:
                host: assets_database
                port: 5432
                name: assets
                username: assets
                password: assets
        authentication:
            enabled: true
            repository: https://github.com/DigitalState/Authentication.git
            version: 0.2.3
            api:
                host: api.authentication.lab.ds
            adminer:
                host: adminer.authentication.lab.ds
            database:
                host: authentication_database
                port: 5432
                name: authentication
                username: authentication
                password: authentication
        camunda:
            enabled: true
            repository: https://github.com/DigitalState/Camunda.git
            version: 0.1.0
            api:
                host: api.camunda.lab.ds
            username: admin@staff.ds
            password: admin
        cases:
            enabled: true
            repository: https://github.com/DigitalState/Cases.git
            version: 0.2.3
            api:
                host: api.cases.lab.ds
            adminer:
                host: adminer.cases.lab.ds
            database:
                host: cases_database
                port: 5432
                name: cases
                username: cases
                password: cases
        cms:
            enabled: true
            repository: https://github.com/DigitalState/Cms.git
            version: 0.2.3
            api:
                host: api.cms.lab.ds
            adminer:
                host: adminer.cms.lab.ds
            database:
                host: cms_database
                port: 5432
                name: cms
                username: cms
                password: cms
        core:
            enabled: true
            repository: https://github.com/DigitalState/Core.git
            version: 0.1.0
        discovery:
            enabled: true
            repository: https://github.com/DigitalState/Discovery.git
            version: 0.1.0
            api:
                host: api.discovery.lab.ds
        documentation:
            enabled: true
            repository: https://github.com/DigitalState/Documentation.git
            version: 0.1.0
        formio:
            enabled: true
            repository: https://github.com/DigitalState/Formio.git
            version: 0.1.5
            api:
                host: api.formio.lab.ds
            username: admin@staff.ds
            password: admin
        guide:
            enabled: true
            repository: https://github.com/DigitalState/Guide.git
            version: 0.1.0
        identities:
            enabled: true
            repository: https://github.com/DigitalState/Identities.git
            version: 0.2.3
            api:
                host: api.identities.lab.ds
            adminer:
                host: adminer.identities.lab.ds
            database:
                host: identities_database
                port: 5432
                name: identities
                username: identities
                password: identities
        interactions:
            enabled: false
            repository: https://github.com/DigitalState/Interactions.git
            version: 0.1.0
            api:
                host: api.interactions.lab.ds
            adminer:
                host: adminer.interactions.lab.ds
            database:
                host: interactions_database
                port: 5432
                name: interactions
                username: interactions
                password: interactions
        logs:
            enabled: false
            repository: https://github.com/DigitalState/Logs.git
            version: 0.1.0
            api:
                host: api.logs.lab.ds
        monitor:
            enabled: false
            repository: https://github.com/DigitalState/Monitor.git
            version: 0.1.0
            host: monitor.lab.ds
        portal:
            enabled: true
            version: 0.1.6
            repository: https://github.com/DigitalState/Portal.git
            host: portal.lab.ds
        proxy:
            enabled: true
            repository: https://github.com/DigitalState/Proxy.git
            version: 0.1.0
            port: 80
        records:
            enabled: true
            repository: https://github.com/DigitalState/Records.git
            version: 0.2.3
            api:
                host: api.records.lab.ds
            adminer:
                host: adminer.records.lab.ds
            database:
                host: records_database
                port: 5432
                name: records
                username: records
                password: records
        services:
            enabled: true
            repository: https://github.com/DigitalState/Services.git
            version: 0.2.3
            api:
                host: api.services.lab.ds
            adminer:
                host: adminer.services.lab.ds
            database:
                host: services_database
                port: 5432
                name: services
                username: services
                password: services
        tasks:
            enabled: false
            repository: https://github.com/DigitalState/Tasks.git
            version: 0.2.3
            api:
                host: api.tasks.lab.ds
            adminer:
                host: adminer.tasks.lab.ds
            database:
                host: tasks_database
                port: 5432
                name: tasks
                username: tasks
                password: tasks
        topics:
            enabled: false
            repository: https://github.com/DigitalState/Topics.git
            version: 0.1.0
            api:
                host: api.topics.lab.ds
            adminer:
                host: adminer.topics.lab.ds
            database:
                host: topics_database
                port: 5432
                name: topics
                username: topics
                password: topics
        ui:
            enabled: true
            repository: https://github.com/DigitalState/Ui.git
            version: 0.1.0
