all:
    hosts:
        server:
            ansible_connection: local

    vars:
        ### General ###########################################################

        jwt_private_key: /root/resource/security/jwt/lab/key
        jwt_public_key: /root/resource/security/jwt/lab/key.pub
        jwt_key_pass_phrase: ~

        fixtures: dev

        ### Documentation #####################################################

        documentation: enabled
        documentation_version: master

        ### Guide #############################################################

        guide: enabled
        guide_version: master

        ### Proxy #############################################################

        proxy: enabled
        proxy_version: develop

        ### Assets ############################################################

        assets: enabled
        assets_version: develop
        assets_host: api.assets.ds

        ### Authentication ####################################################

        authentication: enabled
        authentication_version: develop
        authentication_host: api.authentication.ds

        ### Camunda ###########################################################

        camunda: enabled
        camunda_version: develop
        camunda_host: api.camunda.ds

        ### Cases #############################################################

        cases: enabled
        cases_version: develop
        cases_host: api.cases.ds

        ### Cms ###############################################################

        cms: enabled
        cms_version: develop
        cms_host: api.cms.ds

        ### Discovery #########################################################

        discovery: enabled
        discovery_version: develop
        discovery_host: api.discovery.ds

        ### Formio ############################################################

        formio: enabled
        formio_version: develop
        formio_host: api.formio.ds

        ### Identities ########################################################

        identities: enabled
        identities_version: develop
        identities_host: api.identities.ds

        ### Interactions ######################################################

        interactions: enabled
        interactions_version: develop
        interactions_host: api.interactions.ds

        ### Logs ##############################################################

        logs: enabled
        logs_version: develop
        logs_host: api.logs.ds

        ### Records ###########################################################

        records: enabled
        records_version: develop
        records_host: api.records.ds

        ### Services ##########################################################

        services: enabled
        services_version: develop
        services_host: api.services.ds

        ### Tasks #############################################################

        tasks: enabled
        tasks_version: develop
        tasks_host: api.tasks.ds

        ### Topics ############################################################

        topics: enabled
        topics_version: develop
        topics_host: api.topics.ds

        ### Core ##############################################################

        core: enabled
        core_version: develop

        ### Admin #############################################################

        admin: enabled
        admin_version: develop

        ### Monitor ###########################################################

        monitor: enabled
        monitor_version: develop

        ### Portal ############################################################

        portal: enabled
        portal_version: develop

        ### Ui ################################################################

        ui: enabled
        ui_version: develop
