all:
  hosts:
    server:
      ansible_connection: local

  vars:
    edition: community

    documentation_version: master
    guide_version: master
    api_version: develop
    assets_version: develop
    authentication_version: develop
    camunda_version: develop
    cases_version: develop
    cms_version: develop
    core_version: develop
    discovery_version: develop
    formio_version: develop
    identities_version: develop
    interactions_version: develop
    logs_version: develop
    records_version: develop
    services_version: develop
    tasks_version: develop
    topics_version: develop
    admin_version: develop
    monitor_version: develop
    portal_version: develop
    ui_version: develop

    jwt_private_key: /root/resource/security/jwt/lab/key
    jwt_public_key: /root/resource/security/jwt/lab/key.pub
    jwt_key_pass_phrase: ~
