all:
    hosts:
        server:
            ansible_connection: local

    vars:
        ### Configuration #####################################################

        jwt_private_key: /root/resource/security/jwt/lab/key
        jwt_public_key: /root/resource/security/jwt/lab/key.pub
        jwt_key_pass_phrase: ~

        fixtures: dev

        ### Resource ##########################################################

        documentation: enabled
        documentation_version: master

        guide: enabled
        guide_version: master

        ### Service ###########################################################

        api: enabled
        api_version: develop

        assets: enabled
        assets_version: develop
        assets_host: api.assets.ds

        authentication: enabled
        authentication_version: develop
        authentication_host: api.authentication.ds

        camunda: enabled
        camunda_version: develop
        camunda_host: api.camunda.ds

        cases: enabled
        cases_version: develop
        cases_host: api.cases.ds

        cms: enabled
        cms_version: develop
        cms_host: api.cms.ds

        discovery: enabled
        discovery_version: develop
        discovery_host: api.discovery.ds

        formio: enabled
        formio_version: develop
        formio_host: api.formio.ds

        identities: enabled
        identities_version: develop
        identities_host: api.identities.ds

        interactions: enabled
        interactions_version: develop
        interactions_host: api.interactions.ds

        logs: enabled
        logs_version: develop
        logs_host: api.logs.ds

        records: enabled
        records_version: develop
        records_host: api.records.ds

        services: enabled
        services_version: develop
        services_host: api.services.ds

        tasks: enabled
        tasks_version: develop
        tasks_host: api.tasks.ds

        topics: enabled
        topics_version: develop
        topics_host: api.topics.ds

        core: enabled
        core_version: develop

        ### Spa ###############################################################

        admin: enabled
        admin_version: develop

        monitor: enabled
        monitor_version: develop

        portal: enabled
        portal_version: develop

        ui: enabled
        ui_version: develop

        #######################################################################
