all:
    hosts:
        server:
            ansible_connection: local

    vars:
        documentation: master
        guide: master
        api: develop
        assets: develop
        authentication: develop
        camunda: develop
        cases: develop
        cms: develop
        core: develop
        discovery: develop
        formio: develop
        identities: develop
        interactions: develop
        logs: develop
        records: develop
        services: develop
        tasks: develop
        topics: develop
        admin: develop
        monitor: develop
        portal: develop
        ui: develop

        jwt_private_key: /root/resource/security/jwt/lab/key
        jwt_public_key: /root/resource/security/jwt/lab/key.pub
        jwt_key_pass_phrase: ~

        fixtures: dev
