---
- name: Compile discovery/configure task list
  hosts: platform
  become: true
  tasks:
    - name: Compile files
      compile:
        app: '{{ app }}'
        directory: /etc/ansible/task/app/*
        task: discovery/configure
      register: _result
  tags: [always]

- name: Configure discovery settings
  hosts: server
  become: true
  tasks:
    - name: Include compiled task list
      include_tasks: '{{ _file }}'
      with_items: '{{ hostvars["platform"]["_result"]["tasks"] }}'
      loop_control:
        loop_var: _file
      tags: [always]
    - name: Configure discovery domain mapping
      include_tasks: /etc/ansible/task/app/discovery/map/configure.yml
      tags: [always]
