---
- block:
    - name: Down records container
      docker_service:
        project_src: /srv/records
        files:
          - docker-compose.yml
          - 'docker-compose.{{ records_env }}.yml'
        state: absent
        remove_volumes: '{{ "no" if records_persistent else "yes" }}'
  tags: [records]
