---
_files: ['docker-compose.yml']
_namespace: ds
_directory: /srv/services
_network: ds_proxy_default
_proxy_host: 127.0.0.1
_database_host: services_database
_database_name: services
_database_user: services
_database_password: ~
_database_ui_host: ui.database.services.ds
_api_name: services
_api_env: prod
_api_secret: ''
_api_host: api.services.ds
_api_jwt_pass_phrase: ~
_api_discovery_adapter: consul
_api_discovery_consul_host: api.discovery.ds
_api_discovery_consul_credentials: ~
_api_discovery_env_services: ~
_api_discovery_env_configs: ~
_api_encryption: ~
_api_system_username: system
_api_system_password: ~
_mock_discovery_host: discovery.mock.services.ds
_mock_workflow_host: workflow.mock.services.ds
