---
- name: Up identities container
  docker_service:
      project_src: /srv/identities
      state: present

- name: Waiting for identities container to finalize installation
  shell:
      cmd: docker-compose exec -T php pidof php-fpm | cat
      chdir: /srv/identities
  register: output
  until: output.stdout|match('^[0-9]+(\s[0-9]+)*$')
  retries: 60
  delay: 10
