---
- name: Set cases config
  shell:
      cmd: 'docker-compose exec cases_php bin/console ds:config:set {{ item.key }} {{ item.value }} | cat'
      chdir: /srv/service/cases
  with_dict: '{{ config }}'
