---
portal_env_file: ~
portal_compose_project_name: ds_portal
portal_network: ds_default
portal_proxy_host: 127.0.0.1
portal_virtual_host: portal.ds
portal_directory: /srv/portal
portal_discovery_host: api.discovery.ds
