---
assets:
  enabled: true
  repository: https://github.com/DigitalState/Assets.git
  version: 0.16.2
  api:
    host: api.assets.prod.ds
  database:
    host: assets_database
    name: assets
    user: assets
    password: assets
    ui:
      host: ui.database.assets.prod.ds
  mock:
    discovery:
      host: discovery.mock.assets.prod.ds
  docker:
    - docker-compose.yml
    - docker-compose.prod.yml
    - /root/docker/assets/docker-compose.yml
    - /root/docker/assets/docker-compose.prod.yml
    - /root/docker/api.prod.yml
    - /root/docker/php.prod.yml
