---
authentication:
  enabled: true
  repository: https://github.com/DigitalState/Authentication.git
  version: 0.7.0
  api:
    host: api.authentication.prod.ds
  adminer:
    host: adminer.authentication.prod.ds
  rebrow:
    host: rebrow.authentication.prod.ds
  database:
    host: authentication_database
    port: 5432
    name: authentication
    username: authentication
    password: ~
  attributes:
    access: true
    tenant: true
