---
authentication:
  enabled: true
  repository: https://github.com/DigitalState/Authentication.git
  version: 0.15.0
  api:
    host: api.authentication.prod.ds
  database:
    host: authentication_database
    name: authentication
    user: authentication
    password: ~
    ui:
      host: ui.database.authentication.prod.ds
  docker:
    - docker-compose.yml
    - docker-compose.prod.yml
    - /root/docker/authentication/docker-compose.yml
    - /root/docker/authentication/docker-compose.prod.yml
    - /root/docker/api.prod.yml
    - /root/docker/php.prod.yml
