---
cases:
  enabled: true
  repository: https://github.com/DigitalState/Cases.git
  version: 0.16.2
  api:
    host: api.cases.prod.ds
  database:
    host: cases_database
    name: cases
    user: cases
    password: cases
    ui:
      host: ui.database.cases.prod.ds
  mock:
    discovery:
      host: discovery.mock.cases.prod.ds
  docker:
    - docker-compose.yml
    - docker-compose.prod.yml
    - /root/docker/cases/docker-compose.yml
    - /root/docker/cases/docker-compose.prod.yml
    - /root/docker/api.prod.yml
    - /root/docker/php.prod.yml
