---
cases:
  enabled: true
  repository: https://github.com/DigitalState/Cases.git
  version: 0.8.0
  api:
    host: api.cases.prod.ds
  database:
    host: cases_database
    port: 5432
    name: cases
    username: cases
    password: ~
    ui:
      host: ui.database.cases.prod.ds
  cache:
    ui:
      host: ui.cache.cases.prod.ds
