---
cms:
  enabled: true
  repository: https://github.com/DigitalState/Cms.git
  version: 0.7.0
  api:
    host: api.cms.prod.ds
  adminer:
    host: adminer.cms.prod.ds
  rebrow:
    host: rebrow.cms.prod.ds
  database:
    host: cms_database
    port: 5432
    name: cms
    username: cms
    password: ~
