---
formio:
  enabled: true
  order: -10
  repository: https://github.com/DigitalState/Formio.git
  version: 0.17.0
  api:
    host: api.formio.prod.ds
    admin:
      user: admin@staff.ds
      password: admin
  database:
    ui:
      host: ui.database.formio.prod.ds
  docker:
    - docker-compose.yml
    - docker-compose.prod.yml
    - /root/docker/formio/docker-compose.yml
    - /root/docker/formio/docker-compose.prod.yml
