---
forms:
  enabled: true
  repository: https://github.com/DigitalState/Forms.git
  version: 0.14.0
  api:
    host: api.forms.prod.ds
  database:
    host: forms_database
    port: 5432
    name: forms
    username: forms
    password: ~
    ui:
      host: ui.database.forms.prod.ds
  cache:
    ui:
      host: ui.cache.forms.prod.ds
