---
forms:
  enabled: true
  repository: https://github.com/DigitalState/Forms.git
  version: 0.8.0
  api:
    host: api.forms.prod.ds
  adminer:
    host: adminer.forms.prod.ds
  rebrow:
    host: rebrow.forms.prod.ds
  database:
    host: forms_database
    port: 5432
    name: forms
    username: forms
    password: ~
  attributes:
    access: true
    tenant: true
