---
proxy:
  enabled: true
  order: -30
  repository: https://github.com/DigitalState/Proxy.git
  version: 0.16.1
  port: 80
  discovery:
    token: ~
  ui:
    port: 81
  docker:
    - docker-compose.yml
    - docker-compose.prod.yml
    - /root/docker/proxy/docker-compose.yml
    - /root/docker/proxy/docker-compose.prod.yml
