---
records:
  enabled: true
  repository: https://github.com/DigitalState/Records.git
  version: 0.16.0
  api:
    host: api.records.prod.ds
  database:
    host: records_database
    name: records
    user: records
    password: ~
    ui:
      host: ui.database.records.prod.ds
  mock:
    discovery:
      host: discovery.mock.records.prod.ds
  docker:
    - docker-compose.yml
    - docker-compose.prod.yml
    - /root/docker/records/docker-compose.yml
    - /root/docker/records/docker-compose.prod.yml
    - /root/docker/api.prod.yml
    - /root/docker/php.prod.yml
