---
services:
  enabled: true
  repository: https://github.com/DigitalState/Services.git
  version: 0.16.3
  api:
    host: api.services.prod.ds
  database:
    host: services_database
    name: services
    user: services
    password: services
    ui:
      host: ui.database.services.prod.ds
  mock:
    discovery:
      host: discovery.mock.services.prod.ds
    workflow:
      host: workflow.mock.services.prod.ds
  docker:
    - docker-compose.yml
    - docker-compose.prod.yml
    - /root/docker/services/docker-compose.yml
    - /root/docker/services/docker-compose.prod.yml
    - /root/docker/api.prod.yml
    - /root/docker/php.prod.yml
