---
tasks:
  enabled: false
  repository: https://github.com/DigitalState/Tasks.git
  version: 0.16.0
  api:
    host: api.tasks.prod.ds
  database:
    host: tasks_database
    name: tasks
    user: tasks
    password: ~
    ui:
      host: ui.database.tasks.prod.ds
  mock:
    discovery:
      host: discovery.mock.tasks.prod.ds
  docker:
    - docker-compose.yml
    - docker-compose.prod.yml
    - /root/docker/tasks/docker-compose.yml
    - /root/docker/tasks/docker-compose.prod.yml
    - /root/docker/api.prod.yml
    - /root/docker/php.prod.yml
