---
tenants:
  enabled: false
  repository: https://github.com/DigitalState/Tenants.git
  version: 0.7.0
  api:
    host: api.tenants.prod.ds
  adminer:
    host: adminer.tenants.prod.ds
  rebrow:
    host: rebrow.tenants.prod.ds
  database:
    host: tenants_database
    port: 5432
    name: tenants
    username: tenants
    password: ~
