---
tenants:
  enabled: true
  repository: https://github.com/DigitalState/Tenants.git
  version: 0.15.0
  api:
    host: api.tenants.prod.ds
  database:
    host: tenants_database
    name: tenants
    user: tenants
    password: ~
    ui:
      host: ui.database.tenants.prod.ds
  docker:
    - docker-compose.yml
    - docker-compose.prod.yml
    - /root/docker/tenants/docker-compose.yml
    - /root/docker/tenants/docker-compose.prod.yml
    - /root/docker/api.prod.yml
    - /root/docker/php.prod.yml
