---
topics:
  enabled: false
  repository: https://github.com/DigitalState/Topics.git
  version: 0.1.0
  api:
    host: api.topics.prod.ds
  adminer:
    host: adminer.topics.prod.ds
  rebrow:
    host: rebrow.topics.prod.ds
  database:
    host: topics_database
    port: 5432
    name: topics
    username: topics
    password: ~
