---
workflow:
  enabled: true
  order: -10
  repository: https://github.com/DigitalState/Workflow.git
  version: 0.15.0
  api:
    host: api.workflow.prod.ds
    admin:
      user: admin
      password: ~
  database:
    host: workflow_database
    port: 5432
    name: workflow
    user: workflow
    password: workflow
    ui:
      host: ui.database.workflow.prod.ds
  docker:
    - docker-compose.yml
    - docker-compose.prod.yml
    - /root/docker/config/api/extra_hosts.prod.yml
    - /root/docker/workflow.yml
