---
- block:
    - name: Create formio repository branch
      include_role:
        name: app/formio/repository/branch/create
      vars:
        _repository: '{{ app.formio.repository }}'
        _branch: '{{ branch }}'
  when: app.formio.enabled
  tags: [formio]
