---
- block:
    - name: Retrieve proxy container ip
      include_tasks: /etc/ansible/task/app/proxy/container/property/ip.yml
    - name: Retrieve discovery container ip
      include_tasks: /etc/ansible/task/app/discovery/container/property/ip.yml
    - name: Up records container
      include_role:
        name: app/records/container/up
      vars:
        _files: '{{ app.records.docker|list }}'
        _namespace: '{{ namespace }}'
        _directory: '{{ directory }}/records'
        _network: '{{ namespace }}_proxy_default'
        _proxy_host: '{{ proxy_container_ip.stdout }}'
        _database_host: '{{ app.records.database.host }}'
        _database_name: '{{ app.records.database.name }}'
        _database_username: '{{ app.records.database.username }}'
        _database_password: '{{ app.records.database.password }}'
        _database_ui_host: '{{ app.records.database.ui.host }}'
        _api_env: '{{ env }}'
        _api_secret: '{{ encryption.secret }}'
        _api_host: '{{ app.records.api.host }}'
        _api_discovery_host: '{{ discovery_container_ip.stdout }}:8500'
        _api_discovery_credential: '{{ app.discovery.token.master }}'
        _api_encryption: '{{ encryption.encryption }}'
        _api_system_username: '{{ system.username }}'
        _api_system_password: '{{ system.password }}'
  when: app.records.enabled
  tags: [records]
