version: '3.4'

services:
  api:
    extra_hosts:
      - 'api.assets.test.ds:${PROXY_HOST}'
      - 'api.authentication.test.ds:${PROXY_HOST}'
      - 'api.cases.test.ds:${PROXY_HOST}'
      - 'api.cms.test.ds:${PROXY_HOST}'
      - 'api.discovery.test.ds:${PROXY_HOST}'
      - 'api.formio.test.ds:${PROXY_HOST}'
      - 'api.forms.test.ds:${PROXY_HOST}'
      - 'api.identities.test.ds:${PROXY_HOST}'
      - 'api.microservice.test.ds:${PROXY_HOST}'
      - 'api.records.test.ds:${PROXY_HOST}'
      - 'api.services.test.ds:${PROXY_HOST}'
      - 'api.tasks.test.ds:${PROXY_HOST}'
      - 'api.tenants.test.ds:${PROXY_HOST}'
      - 'api.workflow.test.ds:${PROXY_HOST}'
