version: '3.4'

x-dns: &dns
  - 'api.assets.prod.ds:${PROXY_HOST}'
  - 'api.authentication.prod.ds:${PROXY_HOST}'
  - 'api.camunda.prod.ds:${PROXY_HOST}'
  - 'api.cases.prod.ds:${PROXY_HOST}'
  - 'api.cms.prod.ds:${PROXY_HOST}'
  - 'api.discovery.prod.ds:${PROXY_HOST}'
  - 'api.formio.prod.ds:${PROXY_HOST}'
  - 'api.forms.prod.ds:${PROXY_HOST}'
  - 'api.identities.prod.ds:${PROXY_HOST}'
  - 'api.microservice.prod.ds:${PROXY_HOST}'
  - 'api.records.prod.ds:${PROXY_HOST}'
  - 'api.services.prod.ds:${PROXY_HOST}'
  - 'api.tasks.prod.ds:${PROXY_HOST}'
  - 'api.tenants.prod.ds:${PROXY_HOST}'
