---
- block:
    - name: Delete identities repository branch
      include_role:
        name: app/identities/repository/branch/delete
      vars:
        _repository: '{{ app.identities.repository }}'
        _branch: '{{ branch }}'
  when: app.identities.enabled
  tags: [identities]
