---
- block:
    - name: Gather information for portal container
      include_tasks: /etc/ansible/task/app/proxy/container/info.yml
    - name: Up portal container
      include_role:
        name: app/portal/container/up
      vars:
        _env: '{{ env }}'
        _compose_project_name: '{{ namespace }}portal'
        _network: '{{ namespace }}proxy_default'
        _proxy_host: '{{ proxy_container_info_ip.stdout }}'
        _virtual_host: '{{ app.portal.host }}'
        _discovery_host: '{{ app.discovery.api.host }}'
        _directory: '{{ directory }}/portal'
  when: app.portal.enabled
  tags: [portal]
