---
- name: Configure proxy host environment variable
  lineinfile:
      path: /srv/service/records/.env
      regexp: '^PROXY_HOST='
      line: 'PROXY_HOST={{ proxy_host }}'

- name: Configure records host environment variable
  lineinfile:
      path: /srv/service/records/.env
      regexp: '^VIRTUAL_HOST='
      line: 'VIRTUAL_HOST={{ records_host }}'
