---
- name: Set identities config
  shell:
      cmd: 'docker-compose exec identities_php bin/console ds:config:set {{ item.key }} {{ item.value }} | cat'
      chdir: /srv/service/identities
  with_dict: '{{ config }}'
